//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Department_WebService
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:microsoft-dynamics-schemas/page/department", ConfigurationName="Department_WebService.Department_Service")]
    public interface Department_Service
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/department:GetRecIdFromKey", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Department_WebService.GetRecIdFromKeyResponse> GetRecIdFromKeyAsync(Department_WebService.GetRecIdFromKeyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/department:IsUpdated", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Department_WebService.IsUpdatedResponse> IsUpdatedAsync(Department_WebService.IsUpdatedRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/department:Read", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Department_WebService.ReadResponse> ReadAsync(Department_WebService.ReadRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/department:ReadByRecId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Department_WebService.ReadByRecIdResponse> ReadByRecIdAsync(Department_WebService.ReadByRecIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/department:ReadMultiple", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Department_WebService.ReadMultipleResponse> ReadMultipleAsync(Department_WebService.ReadMultipleRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetRecIdFromKey", WrapperNamespace="urn:microsoft-dynamics-schemas/page/department", IsWrapped=true)]
    public partial class GetRecIdFromKeyRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/department", Order=0)]
        public string Key;
        
        public GetRecIdFromKeyRequest()
        {
        }
        
        public GetRecIdFromKeyRequest(string Key)
        {
            this.Key = Key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetRecIdFromKey_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/department", IsWrapped=true)]
    public partial class GetRecIdFromKeyResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/department", Order=0)]
        public string GetRecIdFromKey_Result;
        
        public GetRecIdFromKeyResponse()
        {
        }
        
        public GetRecIdFromKeyResponse(string GetRecIdFromKey_Result)
        {
            this.GetRecIdFromKey_Result = GetRecIdFromKey_Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IsUpdated", WrapperNamespace="urn:microsoft-dynamics-schemas/page/department", IsWrapped=true)]
    public partial class IsUpdatedRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/department", Order=0)]
        public string Key;
        
        public IsUpdatedRequest()
        {
        }
        
        public IsUpdatedRequest(string Key)
        {
            this.Key = Key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IsUpdated_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/department", IsWrapped=true)]
    public partial class IsUpdatedResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/department", Order=0)]
        public bool IsUpdated_Result;
        
        public IsUpdatedResponse()
        {
        }
        
        public IsUpdatedResponse(bool IsUpdated_Result)
        {
            this.IsUpdated_Result = IsUpdated_Result;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/department")]
    public partial class Department
    {
        
        private string keyField;
        
        private string primary_KeyField;
        
        private string nameField;
        
        private string name_2Field;
        
        private string addressField;
        
        private string address_2Field;
        
        private string cityField;
        
        private string phone_NoField;
        
        private string phone_No_2Field;
        
        private string telex_NoField;
        
        private string fax_NoField;
        
        private string giro_NoField;
        
        private string bank_NameField;
        
        private string bank_Branch_NoField;
        
        private string bank_Account_NoField;
        
        private string payment_Routing_NoField;
        
        private string customs_Permit_NoField;
        
        private System.DateTime customs_Permit_DateField;
        
        private bool customs_Permit_DateFieldSpecified;
        
        private string vAT_Registration_NoField;
        
        private string registration_NoField;
        
        private string telex_Answer_BackField;
        
        private string ship_to_NameField;
        
        private string ship_to_Name_2Field;
        
        private string ship_to_AddressField;
        
        private string ship_to_Address_2Field;
        
        private string ship_to_CityField;
        
        private string ship_to_ContactField;
        
        private string location_CodeField;
        
        private string post_CodeField;
        
        private string countyField;
        
        private string ship_to_Post_CodeField;
        
        private string ship_to_CountyField;
        
        private string e_MailField;
        
        private string home_PageField;
        
        private string country_Region_CodeField;
        
        private string ship_to_Country_Region_CodeField;
        
        private string iBANField;
        
        private string sWIFT_CodeField;
        
        private string industrial_ClassificationField;
        
        private string iC_Partner_CodeField;
        
        private IC_Inbox_Type iC_Inbox_TypeField;
        
        private bool iC_Inbox_TypeFieldSpecified;
        
        private string iC_Inbox_DetailsField;
        
        private System_Indicator system_IndicatorField;
        
        private bool system_IndicatorFieldSpecified;
        
        private string custom_System_Indicator_TextField;
        
        private System_Indicator_Style system_Indicator_StyleField;
        
        private bool system_Indicator_StyleFieldSpecified;
        
        private bool allow_Blank_Payment_InfoField;
        
        private bool allow_Blank_Payment_InfoFieldSpecified;
        
        private string gLNField;
        
        private System.DateTime created_DateTimeField;
        
        private bool created_DateTimeFieldSpecified;
        
        private bool demo_CompanyField;
        
        private bool demo_CompanyFieldSpecified;
        
        private string responsibility_CenterField;
        
        private string check_Avail_Period_CalcField;
        
        private Check_Avail_Time_Bucket check_Avail_Time_BucketField;
        
        private bool check_Avail_Time_BucketFieldSpecified;
        
        private string base_Calendar_CodeField;
        
        private string cal_Convergence_Time_FrameField;
        
        private bool show_Chart_On_RoleCenterField;
        
        private bool show_Chart_On_RoleCenterFieldSpecified;
        
        private string bank_Creditor_NoField;
        
        private string tS_User_NoField;
        
        private string sE_No_DKMMField;
        
        private string fIK_No_DKMMField;
        
        private string municipal_CodeField;
        
        private string municipal_NameField;
        
        private string global_Dimension_1_CodeField;
        
        private int lesson_DurationField;
        
        private bool lesson_DurationFieldSpecified;
        
        private int lesson_Break_DurationField;
        
        private bool lesson_Break_DurationFieldSpecified;
        
        private int school_NoField;
        
        private bool school_NoFieldSpecified;
        
        private string school_Manager_NoField;
        
        private string school_Manager_First_NameField;
        
        private string school_Manager_Sur_NameField;
        
        private string department_VAT_Reg_NoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Key
        {
            get
            {
                return this.keyField;
            }
            set
            {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Primary_Key
        {
            get
            {
                return this.primary_KeyField;
            }
            set
            {
                this.primary_KeyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Name_2
        {
            get
            {
                return this.name_2Field;
            }
            set
            {
                this.name_2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Address
        {
            get
            {
                return this.addressField;
            }
            set
            {
                this.addressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Address_2
        {
            get
            {
                return this.address_2Field;
            }
            set
            {
                this.address_2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string City
        {
            get
            {
                return this.cityField;
            }
            set
            {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Phone_No
        {
            get
            {
                return this.phone_NoField;
            }
            set
            {
                this.phone_NoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string Phone_No_2
        {
            get
            {
                return this.phone_No_2Field;
            }
            set
            {
                this.phone_No_2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string Telex_No
        {
            get
            {
                return this.telex_NoField;
            }
            set
            {
                this.telex_NoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string Fax_No
        {
            get
            {
                return this.fax_NoField;
            }
            set
            {
                this.fax_NoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string Giro_No
        {
            get
            {
                return this.giro_NoField;
            }
            set
            {
                this.giro_NoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string Bank_Name
        {
            get
            {
                return this.bank_NameField;
            }
            set
            {
                this.bank_NameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string Bank_Branch_No
        {
            get
            {
                return this.bank_Branch_NoField;
            }
            set
            {
                this.bank_Branch_NoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string Bank_Account_No
        {
            get
            {
                return this.bank_Account_NoField;
            }
            set
            {
                this.bank_Account_NoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string Payment_Routing_No
        {
            get
            {
                return this.payment_Routing_NoField;
            }
            set
            {
                this.payment_Routing_NoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string Customs_Permit_No
        {
            get
            {
                return this.customs_Permit_NoField;
            }
            set
            {
                this.customs_Permit_NoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=17)]
        public System.DateTime Customs_Permit_Date
        {
            get
            {
                return this.customs_Permit_DateField;
            }
            set
            {
                this.customs_Permit_DateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Customs_Permit_DateSpecified
        {
            get
            {
                return this.customs_Permit_DateFieldSpecified;
            }
            set
            {
                this.customs_Permit_DateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string VAT_Registration_No
        {
            get
            {
                return this.vAT_Registration_NoField;
            }
            set
            {
                this.vAT_Registration_NoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string Registration_No
        {
            get
            {
                return this.registration_NoField;
            }
            set
            {
                this.registration_NoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string Telex_Answer_Back
        {
            get
            {
                return this.telex_Answer_BackField;
            }
            set
            {
                this.telex_Answer_BackField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public string Ship_to_Name
        {
            get
            {
                return this.ship_to_NameField;
            }
            set
            {
                this.ship_to_NameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public string Ship_to_Name_2
        {
            get
            {
                return this.ship_to_Name_2Field;
            }
            set
            {
                this.ship_to_Name_2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public string Ship_to_Address
        {
            get
            {
                return this.ship_to_AddressField;
            }
            set
            {
                this.ship_to_AddressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public string Ship_to_Address_2
        {
            get
            {
                return this.ship_to_Address_2Field;
            }
            set
            {
                this.ship_to_Address_2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=25)]
        public string Ship_to_City
        {
            get
            {
                return this.ship_to_CityField;
            }
            set
            {
                this.ship_to_CityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=26)]
        public string Ship_to_Contact
        {
            get
            {
                return this.ship_to_ContactField;
            }
            set
            {
                this.ship_to_ContactField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=27)]
        public string Location_Code
        {
            get
            {
                return this.location_CodeField;
            }
            set
            {
                this.location_CodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=28)]
        public string Post_Code
        {
            get
            {
                return this.post_CodeField;
            }
            set
            {
                this.post_CodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=29)]
        public string County
        {
            get
            {
                return this.countyField;
            }
            set
            {
                this.countyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=30)]
        public string Ship_to_Post_Code
        {
            get
            {
                return this.ship_to_Post_CodeField;
            }
            set
            {
                this.ship_to_Post_CodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=31)]
        public string Ship_to_County
        {
            get
            {
                return this.ship_to_CountyField;
            }
            set
            {
                this.ship_to_CountyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=32)]
        public string E_Mail
        {
            get
            {
                return this.e_MailField;
            }
            set
            {
                this.e_MailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=33)]
        public string Home_Page
        {
            get
            {
                return this.home_PageField;
            }
            set
            {
                this.home_PageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=34)]
        public string Country_Region_Code
        {
            get
            {
                return this.country_Region_CodeField;
            }
            set
            {
                this.country_Region_CodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=35)]
        public string Ship_to_Country_Region_Code
        {
            get
            {
                return this.ship_to_Country_Region_CodeField;
            }
            set
            {
                this.ship_to_Country_Region_CodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=36)]
        public string IBAN
        {
            get
            {
                return this.iBANField;
            }
            set
            {
                this.iBANField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=37)]
        public string SWIFT_Code
        {
            get
            {
                return this.sWIFT_CodeField;
            }
            set
            {
                this.sWIFT_CodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=38)]
        public string Industrial_Classification
        {
            get
            {
                return this.industrial_ClassificationField;
            }
            set
            {
                this.industrial_ClassificationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=39)]
        public string IC_Partner_Code
        {
            get
            {
                return this.iC_Partner_CodeField;
            }
            set
            {
                this.iC_Partner_CodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=40)]
        public IC_Inbox_Type IC_Inbox_Type
        {
            get
            {
                return this.iC_Inbox_TypeField;
            }
            set
            {
                this.iC_Inbox_TypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IC_Inbox_TypeSpecified
        {
            get
            {
                return this.iC_Inbox_TypeFieldSpecified;
            }
            set
            {
                this.iC_Inbox_TypeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=41)]
        public string IC_Inbox_Details
        {
            get
            {
                return this.iC_Inbox_DetailsField;
            }
            set
            {
                this.iC_Inbox_DetailsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=42)]
        public System_Indicator System_Indicator
        {
            get
            {
                return this.system_IndicatorField;
            }
            set
            {
                this.system_IndicatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool System_IndicatorSpecified
        {
            get
            {
                return this.system_IndicatorFieldSpecified;
            }
            set
            {
                this.system_IndicatorFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=43)]
        public string Custom_System_Indicator_Text
        {
            get
            {
                return this.custom_System_Indicator_TextField;
            }
            set
            {
                this.custom_System_Indicator_TextField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=44)]
        public System_Indicator_Style System_Indicator_Style
        {
            get
            {
                return this.system_Indicator_StyleField;
            }
            set
            {
                this.system_Indicator_StyleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool System_Indicator_StyleSpecified
        {
            get
            {
                return this.system_Indicator_StyleFieldSpecified;
            }
            set
            {
                this.system_Indicator_StyleFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=45)]
        public bool Allow_Blank_Payment_Info
        {
            get
            {
                return this.allow_Blank_Payment_InfoField;
            }
            set
            {
                this.allow_Blank_Payment_InfoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Allow_Blank_Payment_InfoSpecified
        {
            get
            {
                return this.allow_Blank_Payment_InfoFieldSpecified;
            }
            set
            {
                this.allow_Blank_Payment_InfoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=46)]
        public string GLN
        {
            get
            {
                return this.gLNField;
            }
            set
            {
                this.gLNField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=47)]
        public System.DateTime Created_DateTime
        {
            get
            {
                return this.created_DateTimeField;
            }
            set
            {
                this.created_DateTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Created_DateTimeSpecified
        {
            get
            {
                return this.created_DateTimeFieldSpecified;
            }
            set
            {
                this.created_DateTimeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=48)]
        public bool Demo_Company
        {
            get
            {
                return this.demo_CompanyField;
            }
            set
            {
                this.demo_CompanyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Demo_CompanySpecified
        {
            get
            {
                return this.demo_CompanyFieldSpecified;
            }
            set
            {
                this.demo_CompanyFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=49)]
        public string Responsibility_Center
        {
            get
            {
                return this.responsibility_CenterField;
            }
            set
            {
                this.responsibility_CenterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=50)]
        public string Check_Avail_Period_Calc
        {
            get
            {
                return this.check_Avail_Period_CalcField;
            }
            set
            {
                this.check_Avail_Period_CalcField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=51)]
        public Check_Avail_Time_Bucket Check_Avail_Time_Bucket
        {
            get
            {
                return this.check_Avail_Time_BucketField;
            }
            set
            {
                this.check_Avail_Time_BucketField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Check_Avail_Time_BucketSpecified
        {
            get
            {
                return this.check_Avail_Time_BucketFieldSpecified;
            }
            set
            {
                this.check_Avail_Time_BucketFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=52)]
        public string Base_Calendar_Code
        {
            get
            {
                return this.base_Calendar_CodeField;
            }
            set
            {
                this.base_Calendar_CodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=53)]
        public string Cal_Convergence_Time_Frame
        {
            get
            {
                return this.cal_Convergence_Time_FrameField;
            }
            set
            {
                this.cal_Convergence_Time_FrameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=54)]
        public bool Show_Chart_On_RoleCenter
        {
            get
            {
                return this.show_Chart_On_RoleCenterField;
            }
            set
            {
                this.show_Chart_On_RoleCenterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Show_Chart_On_RoleCenterSpecified
        {
            get
            {
                return this.show_Chart_On_RoleCenterFieldSpecified;
            }
            set
            {
                this.show_Chart_On_RoleCenterFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=55)]
        public string Bank_Creditor_No
        {
            get
            {
                return this.bank_Creditor_NoField;
            }
            set
            {
                this.bank_Creditor_NoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("T&S_User_No", Order=56)]
        public string TS_User_No
        {
            get
            {
                return this.tS_User_NoField;
            }
            set
            {
                this.tS_User_NoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=57)]
        public string SE_No_DKMM
        {
            get
            {
                return this.sE_No_DKMMField;
            }
            set
            {
                this.sE_No_DKMMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=58)]
        public string FIK_No_DKMM
        {
            get
            {
                return this.fIK_No_DKMMField;
            }
            set
            {
                this.fIK_No_DKMMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=59)]
        public string Municipal_Code
        {
            get
            {
                return this.municipal_CodeField;
            }
            set
            {
                this.municipal_CodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=60)]
        public string Municipal_Name
        {
            get
            {
                return this.municipal_NameField;
            }
            set
            {
                this.municipal_NameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=61)]
        public string Global_Dimension_1_Code
        {
            get
            {
                return this.global_Dimension_1_CodeField;
            }
            set
            {
                this.global_Dimension_1_CodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=62)]
        public int Lesson_Duration
        {
            get
            {
                return this.lesson_DurationField;
            }
            set
            {
                this.lesson_DurationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Lesson_DurationSpecified
        {
            get
            {
                return this.lesson_DurationFieldSpecified;
            }
            set
            {
                this.lesson_DurationFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=63)]
        public int Lesson_Break_Duration
        {
            get
            {
                return this.lesson_Break_DurationField;
            }
            set
            {
                this.lesson_Break_DurationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Lesson_Break_DurationSpecified
        {
            get
            {
                return this.lesson_Break_DurationFieldSpecified;
            }
            set
            {
                this.lesson_Break_DurationFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=64)]
        public int School_No
        {
            get
            {
                return this.school_NoField;
            }
            set
            {
                this.school_NoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool School_NoSpecified
        {
            get
            {
                return this.school_NoFieldSpecified;
            }
            set
            {
                this.school_NoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=65)]
        public string School_Manager_No
        {
            get
            {
                return this.school_Manager_NoField;
            }
            set
            {
                this.school_Manager_NoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=66)]
        public string School_Manager_First_Name
        {
            get
            {
                return this.school_Manager_First_NameField;
            }
            set
            {
                this.school_Manager_First_NameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=67)]
        public string School_Manager_Sur_Name
        {
            get
            {
                return this.school_Manager_Sur_NameField;
            }
            set
            {
                this.school_Manager_Sur_NameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=68)]
        public string Department_VAT_Reg_No
        {
            get
            {
                return this.department_VAT_Reg_NoField;
            }
            set
            {
                this.department_VAT_Reg_NoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/department")]
    public enum IC_Inbox_Type
    {
        
        /// <remarks/>
        File_Location,
        
        /// <remarks/>
        Database,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/department")]
    public enum System_Indicator
    {
        
        /// <remarks/>
        None,
        
        /// <remarks/>
        Custom_Text,
        
        /// <remarks/>
        Company_Information,
        
        /// <remarks/>
        Company,
        
        /// <remarks/>
        Database,
        
        /// <remarks/>
        Company_x002B_Database,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/department")]
    public enum System_Indicator_Style
    {
        
        /// <remarks/>
        Standard,
        
        /// <remarks/>
        Accent1,
        
        /// <remarks/>
        Accent2,
        
        /// <remarks/>
        Accent3,
        
        /// <remarks/>
        Accent4,
        
        /// <remarks/>
        Accent5,
        
        /// <remarks/>
        Accent6,
        
        /// <remarks/>
        Accent7,
        
        /// <remarks/>
        Accent8,
        
        /// <remarks/>
        Accent9,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/department")]
    public enum Check_Avail_Time_Bucket
    {
        
        /// <remarks/>
        Day,
        
        /// <remarks/>
        Week,
        
        /// <remarks/>
        Month,
        
        /// <remarks/>
        Quarter,
        
        /// <remarks/>
        Year,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/department")]
    public partial class Department_Filter
    {
        
        private Department_Fields fieldField;
        
        private string criteriaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Department_Fields Field
        {
            get
            {
                return this.fieldField;
            }
            set
            {
                this.fieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Criteria
        {
            get
            {
                return this.criteriaField;
            }
            set
            {
                this.criteriaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/department")]
    public enum Department_Fields
    {
        
        /// <remarks/>
        Primary_Key,
        
        /// <remarks/>
        Name,
        
        /// <remarks/>
        Name_2,
        
        /// <remarks/>
        Address,
        
        /// <remarks/>
        Address_2,
        
        /// <remarks/>
        City,
        
        /// <remarks/>
        Phone_No,
        
        /// <remarks/>
        Phone_No_2,
        
        /// <remarks/>
        Telex_No,
        
        /// <remarks/>
        Fax_No,
        
        /// <remarks/>
        Giro_No,
        
        /// <remarks/>
        Bank_Name,
        
        /// <remarks/>
        Bank_Branch_No,
        
        /// <remarks/>
        Bank_Account_No,
        
        /// <remarks/>
        Payment_Routing_No,
        
        /// <remarks/>
        Customs_Permit_No,
        
        /// <remarks/>
        Customs_Permit_Date,
        
        /// <remarks/>
        VAT_Registration_No,
        
        /// <remarks/>
        Registration_No,
        
        /// <remarks/>
        Telex_Answer_Back,
        
        /// <remarks/>
        Ship_to_Name,
        
        /// <remarks/>
        Ship_to_Name_2,
        
        /// <remarks/>
        Ship_to_Address,
        
        /// <remarks/>
        Ship_to_Address_2,
        
        /// <remarks/>
        Ship_to_City,
        
        /// <remarks/>
        Ship_to_Contact,
        
        /// <remarks/>
        Location_Code,
        
        /// <remarks/>
        Post_Code,
        
        /// <remarks/>
        County,
        
        /// <remarks/>
        Ship_to_Post_Code,
        
        /// <remarks/>
        Ship_to_County,
        
        /// <remarks/>
        E_Mail,
        
        /// <remarks/>
        Home_Page,
        
        /// <remarks/>
        Country_Region_Code,
        
        /// <remarks/>
        Ship_to_Country_Region_Code,
        
        /// <remarks/>
        IBAN,
        
        /// <remarks/>
        SWIFT_Code,
        
        /// <remarks/>
        Industrial_Classification,
        
        /// <remarks/>
        IC_Partner_Code,
        
        /// <remarks/>
        IC_Inbox_Type,
        
        /// <remarks/>
        IC_Inbox_Details,
        
        /// <remarks/>
        System_Indicator,
        
        /// <remarks/>
        Custom_System_Indicator_Text,
        
        /// <remarks/>
        System_Indicator_Style,
        
        /// <remarks/>
        Allow_Blank_Payment_Info,
        
        /// <remarks/>
        GLN,
        
        /// <remarks/>
        Created_DateTime,
        
        /// <remarks/>
        Demo_Company,
        
        /// <remarks/>
        Responsibility_Center,
        
        /// <remarks/>
        Check_Avail_Period_Calc,
        
        /// <remarks/>
        Check_Avail_Time_Bucket,
        
        /// <remarks/>
        Base_Calendar_Code,
        
        /// <remarks/>
        Cal_Convergence_Time_Frame,
        
        /// <remarks/>
        Show_Chart_On_RoleCenter,
        
        /// <remarks/>
        Bank_Creditor_No,
        
        /// <remarks/>
        T_x0026_S_User_No,
        
        /// <remarks/>
        SE_No_DKMM,
        
        /// <remarks/>
        FIK_No_DKMM,
        
        /// <remarks/>
        Municipal_Code,
        
        /// <remarks/>
        Municipal_Name,
        
        /// <remarks/>
        Global_Dimension_1_Code,
        
        /// <remarks/>
        Lesson_Duration,
        
        /// <remarks/>
        Lesson_Break_Duration,
        
        /// <remarks/>
        School_No,
        
        /// <remarks/>
        School_Manager_No,
        
        /// <remarks/>
        School_Manager_First_Name,
        
        /// <remarks/>
        School_Manager_Sur_Name,
        
        /// <remarks/>
        Department_VAT_Reg_No,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Read", WrapperNamespace="urn:microsoft-dynamics-schemas/page/department", IsWrapped=true)]
    public partial class ReadRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/department", Order=0)]
        public string Primary_Key;
        
        public ReadRequest()
        {
        }
        
        public ReadRequest(string Primary_Key)
        {
            this.Primary_Key = Primary_Key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Read_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/department", IsWrapped=true)]
    public partial class ReadResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/department", Order=0)]
        public Department_WebService.Department Department;
        
        public ReadResponse()
        {
        }
        
        public ReadResponse(Department_WebService.Department Department)
        {
            this.Department = Department;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadByRecId", WrapperNamespace="urn:microsoft-dynamics-schemas/page/department", IsWrapped=true)]
    public partial class ReadByRecIdRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/department", Order=0)]
        public string recId;
        
        public ReadByRecIdRequest()
        {
        }
        
        public ReadByRecIdRequest(string recId)
        {
            this.recId = recId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadByRecId_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/department", IsWrapped=true)]
    public partial class ReadByRecIdResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/department", Order=0)]
        public Department_WebService.Department Department;
        
        public ReadByRecIdResponse()
        {
        }
        
        public ReadByRecIdResponse(Department_WebService.Department Department)
        {
            this.Department = Department;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadMultiple", WrapperNamespace="urn:microsoft-dynamics-schemas/page/department", IsWrapped=true)]
    public partial class ReadMultipleRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/department", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("filter")]
        public Department_WebService.Department_Filter[] filter;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/department", Order=1)]
        public string bookmarkKey;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/department", Order=2)]
        public int setSize;
        
        public ReadMultipleRequest()
        {
        }
        
        public ReadMultipleRequest(Department_WebService.Department_Filter[] filter, string bookmarkKey, int setSize)
        {
            this.filter = filter;
            this.bookmarkKey = bookmarkKey;
            this.setSize = setSize;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadMultiple_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/department", IsWrapped=true)]
    public partial class ReadMultipleResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/department", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Department_WebService.Department[] ReadMultiple_Result;
        
        public ReadMultipleResponse()
        {
        }
        
        public ReadMultipleResponse(Department_WebService.Department[] ReadMultiple_Result)
        {
            this.ReadMultiple_Result = ReadMultiple_Result;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    public interface Department_ServiceChannel : Department_WebService.Department_Service, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    public partial class Department_ServiceClient : System.ServiceModel.ClientBase<Department_WebService.Department_Service>, Department_WebService.Department_Service
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public Department_ServiceClient() : 
                base(Department_ServiceClient.GetDefaultBinding(), Department_ServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.Department_Service.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Department_ServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(Department_ServiceClient.GetBindingForEndpoint(endpointConfiguration), Department_ServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Department_ServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(Department_ServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Department_ServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(Department_ServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Department_ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Department_WebService.GetRecIdFromKeyResponse> Department_WebService.Department_Service.GetRecIdFromKeyAsync(Department_WebService.GetRecIdFromKeyRequest request)
        {
            return base.Channel.GetRecIdFromKeyAsync(request);
        }
        
        public System.Threading.Tasks.Task<Department_WebService.GetRecIdFromKeyResponse> GetRecIdFromKeyAsync(string Key)
        {
            Department_WebService.GetRecIdFromKeyRequest inValue = new Department_WebService.GetRecIdFromKeyRequest();
            inValue.Key = Key;
            return ((Department_WebService.Department_Service)(this)).GetRecIdFromKeyAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Department_WebService.IsUpdatedResponse> Department_WebService.Department_Service.IsUpdatedAsync(Department_WebService.IsUpdatedRequest request)
        {
            return base.Channel.IsUpdatedAsync(request);
        }
        
        public System.Threading.Tasks.Task<Department_WebService.IsUpdatedResponse> IsUpdatedAsync(string Key)
        {
            Department_WebService.IsUpdatedRequest inValue = new Department_WebService.IsUpdatedRequest();
            inValue.Key = Key;
            return ((Department_WebService.Department_Service)(this)).IsUpdatedAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Department_WebService.ReadResponse> Department_WebService.Department_Service.ReadAsync(Department_WebService.ReadRequest request)
        {
            return base.Channel.ReadAsync(request);
        }
        
        public System.Threading.Tasks.Task<Department_WebService.ReadResponse> ReadAsync(string Primary_Key)
        {
            Department_WebService.ReadRequest inValue = new Department_WebService.ReadRequest();
            inValue.Primary_Key = Primary_Key;
            return ((Department_WebService.Department_Service)(this)).ReadAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Department_WebService.ReadByRecIdResponse> Department_WebService.Department_Service.ReadByRecIdAsync(Department_WebService.ReadByRecIdRequest request)
        {
            return base.Channel.ReadByRecIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<Department_WebService.ReadByRecIdResponse> ReadByRecIdAsync(string recId)
        {
            Department_WebService.ReadByRecIdRequest inValue = new Department_WebService.ReadByRecIdRequest();
            inValue.recId = recId;
            return ((Department_WebService.Department_Service)(this)).ReadByRecIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Department_WebService.ReadMultipleResponse> Department_WebService.Department_Service.ReadMultipleAsync(Department_WebService.ReadMultipleRequest request)
        {
            return base.Channel.ReadMultipleAsync(request);
        }
        
        public System.Threading.Tasks.Task<Department_WebService.ReadMultipleResponse> ReadMultipleAsync(Department_WebService.Department_Filter[] filter, string bookmarkKey, int setSize)
        {
            Department_WebService.ReadMultipleRequest inValue = new Department_WebService.ReadMultipleRequest();
            inValue.filter = filter;
            inValue.bookmarkKey = bookmarkKey;
            inValue.setSize = setSize;
            return ((Department_WebService.Department_Service)(this)).ReadMultipleAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.Department_Service))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.Department_Service))
            {
                return new System.ServiceModel.EndpointAddress("https://iqiapimanagement-asa-dev.azure-api.net/department");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return Department_ServiceClient.GetBindingForEndpoint(EndpointConfiguration.Department_Service);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return Department_ServiceClient.GetEndpointAddress(EndpointConfiguration.Department_Service);
        }
        
        public enum EndpointConfiguration
        {
            
            Department_Service,
        }
    }
}
