//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalaryTeacherSpec_WebService
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:microsoft-dynamics-schemas/page/salaryteacherspec", ConfigurationName="SalaryTeacherSpec_WebService.SalaryTeacherSpec_Service")]
    public interface SalaryTeacherSpec_Service
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/salaryteacherspec:Read", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<SalaryTeacherSpec_WebService.ReadResponse> ReadAsync(SalaryTeacherSpec_WebService.ReadRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/salaryteacherspec:ReadByRecId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<SalaryTeacherSpec_WebService.ReadByRecIdResponse> ReadByRecIdAsync(SalaryTeacherSpec_WebService.ReadByRecIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/salaryteacherspec:ReadMultiple", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<SalaryTeacherSpec_WebService.ReadMultipleResponse> ReadMultipleAsync(SalaryTeacherSpec_WebService.ReadMultipleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/salaryteacherspec:IsUpdated", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<SalaryTeacherSpec_WebService.IsUpdatedResponse> IsUpdatedAsync(SalaryTeacherSpec_WebService.IsUpdatedRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/salaryteacherspec:GetRecIdFromKey", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<SalaryTeacherSpec_WebService.GetRecIdFromKeyResponse> GetRecIdFromKeyAsync(SalaryTeacherSpec_WebService.GetRecIdFromKeyRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/salaryteacherspec")]
    public partial class SalaryTeacherSpec
    {
        
        private string keyField;
        
        private string noField;
        
        private string first_NameField;
        
        private string sur_NameField;
        
        private string social_Security_NoField;
        
        private string addressField;
        
        private string address_2Field;
        
        private string post_CodeField;
        
        private string cityField;
        
        private string country_Region_CodeField;
        
        private string e_MailField;
        
        private Employment_Type employment_TypeField;
        
        private bool employment_TypeFieldSpecified;
        
        private Tax_Card_Type tax_Card_TypeField;
        
        private bool tax_Card_TypeFieldSpecified;
        
        private Payslip_Way_of_Delivery payslip_Way_of_DeliveryField;
        
        private bool payslip_Way_of_DeliveryFieldSpecified;
        
        private System.DateTime hiring_DateField;
        
        private bool hiring_DateFieldSpecified;
        
        private System.DateTime termination_DateField;
        
        private bool termination_DateFieldSpecified;
        
        private string bank_Branch_NoField;
        
        private string bank_Account_NoField;
        
        private string phone_NoField;
        
        private string mobile_Phone_NoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Key
        {
            get
            {
                return this.keyField;
            }
            set
            {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string No
        {
            get
            {
                return this.noField;
            }
            set
            {
                this.noField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string First_Name
        {
            get
            {
                return this.first_NameField;
            }
            set
            {
                this.first_NameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Sur_Name
        {
            get
            {
                return this.sur_NameField;
            }
            set
            {
                this.sur_NameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Social_Security_No
        {
            get
            {
                return this.social_Security_NoField;
            }
            set
            {
                this.social_Security_NoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Address
        {
            get
            {
                return this.addressField;
            }
            set
            {
                this.addressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Address_2
        {
            get
            {
                return this.address_2Field;
            }
            set
            {
                this.address_2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Post_Code
        {
            get
            {
                return this.post_CodeField;
            }
            set
            {
                this.post_CodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string City
        {
            get
            {
                return this.cityField;
            }
            set
            {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string Country_Region_Code
        {
            get
            {
                return this.country_Region_CodeField;
            }
            set
            {
                this.country_Region_CodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string E_Mail
        {
            get
            {
                return this.e_MailField;
            }
            set
            {
                this.e_MailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public Employment_Type Employment_Type
        {
            get
            {
                return this.employment_TypeField;
            }
            set
            {
                this.employment_TypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Employment_TypeSpecified
        {
            get
            {
                return this.employment_TypeFieldSpecified;
            }
            set
            {
                this.employment_TypeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public Tax_Card_Type Tax_Card_Type
        {
            get
            {
                return this.tax_Card_TypeField;
            }
            set
            {
                this.tax_Card_TypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Tax_Card_TypeSpecified
        {
            get
            {
                return this.tax_Card_TypeFieldSpecified;
            }
            set
            {
                this.tax_Card_TypeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public Payslip_Way_of_Delivery Payslip_Way_of_Delivery
        {
            get
            {
                return this.payslip_Way_of_DeliveryField;
            }
            set
            {
                this.payslip_Way_of_DeliveryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Payslip_Way_of_DeliverySpecified
        {
            get
            {
                return this.payslip_Way_of_DeliveryFieldSpecified;
            }
            set
            {
                this.payslip_Way_of_DeliveryFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=14)]
        public System.DateTime Hiring_Date
        {
            get
            {
                return this.hiring_DateField;
            }
            set
            {
                this.hiring_DateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Hiring_DateSpecified
        {
            get
            {
                return this.hiring_DateFieldSpecified;
            }
            set
            {
                this.hiring_DateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=15)]
        public System.DateTime Termination_Date
        {
            get
            {
                return this.termination_DateField;
            }
            set
            {
                this.termination_DateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Termination_DateSpecified
        {
            get
            {
                return this.termination_DateFieldSpecified;
            }
            set
            {
                this.termination_DateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string Bank_Branch_No
        {
            get
            {
                return this.bank_Branch_NoField;
            }
            set
            {
                this.bank_Branch_NoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string Bank_Account_No
        {
            get
            {
                return this.bank_Account_NoField;
            }
            set
            {
                this.bank_Account_NoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string Phone_No
        {
            get
            {
                return this.phone_NoField;
            }
            set
            {
                this.phone_NoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string Mobile_Phone_No
        {
            get
            {
                return this.mobile_Phone_NoField;
            }
            set
            {
                this.mobile_Phone_NoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/salaryteacherspec")]
    public enum Employment_Type
    {
        
        /// <remarks/>
        _blank_,
        
        /// <remarks/>
        Permant,
        
        /// <remarks/>
        Hourly_Paid,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/salaryteacherspec")]
    public enum Tax_Card_Type
    {
        
        /// <remarks/>
        _blank_,
        
        /// <remarks/>
        Main_Tax_Card,
        
        /// <remarks/>
        Secondary_Tax_Card,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/salaryteacherspec")]
    public enum Payslip_Way_of_Delivery
    {
        
        /// <remarks/>
        _blank_,
        
        /// <remarks/>
        E_Mail,
        
        /// <remarks/>
        E_Box,
        
        /// <remarks/>
        Paper,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/salaryteacherspec")]
    public partial class SalaryTeacherSpec_Filter
    {
        
        private SalaryTeacherSpec_Fields fieldField;
        
        private string criteriaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public SalaryTeacherSpec_Fields Field
        {
            get
            {
                return this.fieldField;
            }
            set
            {
                this.fieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Criteria
        {
            get
            {
                return this.criteriaField;
            }
            set
            {
                this.criteriaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/salaryteacherspec")]
    public enum SalaryTeacherSpec_Fields
    {
        
        /// <remarks/>
        No,
        
        /// <remarks/>
        First_Name,
        
        /// <remarks/>
        Sur_Name,
        
        /// <remarks/>
        Social_Security_No,
        
        /// <remarks/>
        Address,
        
        /// <remarks/>
        Address_2,
        
        /// <remarks/>
        Post_Code,
        
        /// <remarks/>
        City,
        
        /// <remarks/>
        Country_Region_Code,
        
        /// <remarks/>
        E_Mail,
        
        /// <remarks/>
        Employment_Type,
        
        /// <remarks/>
        Tax_Card_Type,
        
        /// <remarks/>
        Payslip_Way_of_Delivery,
        
        /// <remarks/>
        Hiring_Date,
        
        /// <remarks/>
        Termination_Date,
        
        /// <remarks/>
        Bank_Branch_No,
        
        /// <remarks/>
        Bank_Account_No,
        
        /// <remarks/>
        Phone_No,
        
        /// <remarks/>
        Mobile_Phone_No,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Read", WrapperNamespace="urn:microsoft-dynamics-schemas/page/salaryteacherspec", IsWrapped=true)]
    public partial class ReadRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/salaryteacherspec", Order=0)]
        public string No;
        
        public ReadRequest()
        {
        }
        
        public ReadRequest(string No)
        {
            this.No = No;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Read_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/salaryteacherspec", IsWrapped=true)]
    public partial class ReadResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/salaryteacherspec", Order=0)]
        public SalaryTeacherSpec_WebService.SalaryTeacherSpec SalaryTeacherSpec;
        
        public ReadResponse()
        {
        }
        
        public ReadResponse(SalaryTeacherSpec_WebService.SalaryTeacherSpec SalaryTeacherSpec)
        {
            this.SalaryTeacherSpec = SalaryTeacherSpec;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadByRecId", WrapperNamespace="urn:microsoft-dynamics-schemas/page/salaryteacherspec", IsWrapped=true)]
    public partial class ReadByRecIdRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/salaryteacherspec", Order=0)]
        public string recId;
        
        public ReadByRecIdRequest()
        {
        }
        
        public ReadByRecIdRequest(string recId)
        {
            this.recId = recId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadByRecId_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/salaryteacherspec", IsWrapped=true)]
    public partial class ReadByRecIdResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/salaryteacherspec", Order=0)]
        public SalaryTeacherSpec_WebService.SalaryTeacherSpec SalaryTeacherSpec;
        
        public ReadByRecIdResponse()
        {
        }
        
        public ReadByRecIdResponse(SalaryTeacherSpec_WebService.SalaryTeacherSpec SalaryTeacherSpec)
        {
            this.SalaryTeacherSpec = SalaryTeacherSpec;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadMultiple", WrapperNamespace="urn:microsoft-dynamics-schemas/page/salaryteacherspec", IsWrapped=true)]
    public partial class ReadMultipleRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/salaryteacherspec", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("filter")]
        public SalaryTeacherSpec_WebService.SalaryTeacherSpec_Filter[] filter;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/salaryteacherspec", Order=1)]
        public string bookmarkKey;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/salaryteacherspec", Order=2)]
        public int setSize;
        
        public ReadMultipleRequest()
        {
        }
        
        public ReadMultipleRequest(SalaryTeacherSpec_WebService.SalaryTeacherSpec_Filter[] filter, string bookmarkKey, int setSize)
        {
            this.filter = filter;
            this.bookmarkKey = bookmarkKey;
            this.setSize = setSize;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadMultiple_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/salaryteacherspec", IsWrapped=true)]
    public partial class ReadMultipleResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/salaryteacherspec", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public SalaryTeacherSpec_WebService.SalaryTeacherSpec[] ReadMultiple_Result;
        
        public ReadMultipleResponse()
        {
        }
        
        public ReadMultipleResponse(SalaryTeacherSpec_WebService.SalaryTeacherSpec[] ReadMultiple_Result)
        {
            this.ReadMultiple_Result = ReadMultiple_Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IsUpdated", WrapperNamespace="urn:microsoft-dynamics-schemas/page/salaryteacherspec", IsWrapped=true)]
    public partial class IsUpdatedRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/salaryteacherspec", Order=0)]
        public string Key;
        
        public IsUpdatedRequest()
        {
        }
        
        public IsUpdatedRequest(string Key)
        {
            this.Key = Key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IsUpdated_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/salaryteacherspec", IsWrapped=true)]
    public partial class IsUpdatedResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/salaryteacherspec", Order=0)]
        public bool IsUpdated_Result;
        
        public IsUpdatedResponse()
        {
        }
        
        public IsUpdatedResponse(bool IsUpdated_Result)
        {
            this.IsUpdated_Result = IsUpdated_Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetRecIdFromKey", WrapperNamespace="urn:microsoft-dynamics-schemas/page/salaryteacherspec", IsWrapped=true)]
    public partial class GetRecIdFromKeyRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/salaryteacherspec", Order=0)]
        public string Key;
        
        public GetRecIdFromKeyRequest()
        {
        }
        
        public GetRecIdFromKeyRequest(string Key)
        {
            this.Key = Key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetRecIdFromKey_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/salaryteacherspec", IsWrapped=true)]
    public partial class GetRecIdFromKeyResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/salaryteacherspec", Order=0)]
        public string GetRecIdFromKey_Result;
        
        public GetRecIdFromKeyResponse()
        {
        }
        
        public GetRecIdFromKeyResponse(string GetRecIdFromKey_Result)
        {
            this.GetRecIdFromKey_Result = GetRecIdFromKey_Result;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface SalaryTeacherSpec_ServiceChannel : SalaryTeacherSpec_WebService.SalaryTeacherSpec_Service, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class SalaryTeacherSpec_ServiceClient : System.ServiceModel.ClientBase<SalaryTeacherSpec_WebService.SalaryTeacherSpec_Service>, SalaryTeacherSpec_WebService.SalaryTeacherSpec_Service
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public SalaryTeacherSpec_ServiceClient() : 
                base(SalaryTeacherSpec_ServiceClient.GetDefaultBinding(), SalaryTeacherSpec_ServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.SalaryTeacherSpec_Service.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SalaryTeacherSpec_ServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(SalaryTeacherSpec_ServiceClient.GetBindingForEndpoint(endpointConfiguration), SalaryTeacherSpec_ServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SalaryTeacherSpec_ServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(SalaryTeacherSpec_ServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SalaryTeacherSpec_ServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(SalaryTeacherSpec_ServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SalaryTeacherSpec_ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SalaryTeacherSpec_WebService.ReadResponse> SalaryTeacherSpec_WebService.SalaryTeacherSpec_Service.ReadAsync(SalaryTeacherSpec_WebService.ReadRequest request)
        {
            return base.Channel.ReadAsync(request);
        }
        
        public System.Threading.Tasks.Task<SalaryTeacherSpec_WebService.ReadResponse> ReadAsync(string No)
        {
            SalaryTeacherSpec_WebService.ReadRequest inValue = new SalaryTeacherSpec_WebService.ReadRequest();
            inValue.No = No;
            return ((SalaryTeacherSpec_WebService.SalaryTeacherSpec_Service)(this)).ReadAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SalaryTeacherSpec_WebService.ReadByRecIdResponse> SalaryTeacherSpec_WebService.SalaryTeacherSpec_Service.ReadByRecIdAsync(SalaryTeacherSpec_WebService.ReadByRecIdRequest request)
        {
            return base.Channel.ReadByRecIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<SalaryTeacherSpec_WebService.ReadByRecIdResponse> ReadByRecIdAsync(string recId)
        {
            SalaryTeacherSpec_WebService.ReadByRecIdRequest inValue = new SalaryTeacherSpec_WebService.ReadByRecIdRequest();
            inValue.recId = recId;
            return ((SalaryTeacherSpec_WebService.SalaryTeacherSpec_Service)(this)).ReadByRecIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SalaryTeacherSpec_WebService.ReadMultipleResponse> SalaryTeacherSpec_WebService.SalaryTeacherSpec_Service.ReadMultipleAsync(SalaryTeacherSpec_WebService.ReadMultipleRequest request)
        {
            return base.Channel.ReadMultipleAsync(request);
        }
        
        public System.Threading.Tasks.Task<SalaryTeacherSpec_WebService.ReadMultipleResponse> ReadMultipleAsync(SalaryTeacherSpec_WebService.SalaryTeacherSpec_Filter[] filter, string bookmarkKey, int setSize)
        {
            SalaryTeacherSpec_WebService.ReadMultipleRequest inValue = new SalaryTeacherSpec_WebService.ReadMultipleRequest();
            inValue.filter = filter;
            inValue.bookmarkKey = bookmarkKey;
            inValue.setSize = setSize;
            return ((SalaryTeacherSpec_WebService.SalaryTeacherSpec_Service)(this)).ReadMultipleAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SalaryTeacherSpec_WebService.IsUpdatedResponse> SalaryTeacherSpec_WebService.SalaryTeacherSpec_Service.IsUpdatedAsync(SalaryTeacherSpec_WebService.IsUpdatedRequest request)
        {
            return base.Channel.IsUpdatedAsync(request);
        }
        
        public System.Threading.Tasks.Task<SalaryTeacherSpec_WebService.IsUpdatedResponse> IsUpdatedAsync(string Key)
        {
            SalaryTeacherSpec_WebService.IsUpdatedRequest inValue = new SalaryTeacherSpec_WebService.IsUpdatedRequest();
            inValue.Key = Key;
            return ((SalaryTeacherSpec_WebService.SalaryTeacherSpec_Service)(this)).IsUpdatedAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SalaryTeacherSpec_WebService.GetRecIdFromKeyResponse> SalaryTeacherSpec_WebService.SalaryTeacherSpec_Service.GetRecIdFromKeyAsync(SalaryTeacherSpec_WebService.GetRecIdFromKeyRequest request)
        {
            return base.Channel.GetRecIdFromKeyAsync(request);
        }
        
        public System.Threading.Tasks.Task<SalaryTeacherSpec_WebService.GetRecIdFromKeyResponse> GetRecIdFromKeyAsync(string Key)
        {
            SalaryTeacherSpec_WebService.GetRecIdFromKeyRequest inValue = new SalaryTeacherSpec_WebService.GetRecIdFromKeyRequest();
            inValue.Key = Key;
            return ((SalaryTeacherSpec_WebService.SalaryTeacherSpec_Service)(this)).GetRecIdFromKeyAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.SalaryTeacherSpec_Service))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.SalaryTeacherSpec_Service))
            {
                return new System.ServiceModel.EndpointAddress("https://iqiapimanagement-asa-test.azure-api.net/salaryteacherspec");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return SalaryTeacherSpec_ServiceClient.GetBindingForEndpoint(EndpointConfiguration.SalaryTeacherSpec_Service);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return SalaryTeacherSpec_ServiceClient.GetEndpointAddress(EndpointConfiguration.SalaryTeacherSpec_Service);
        }
        
        public enum EndpointConfiguration
        {
            
            SalaryTeacherSpec_Service,
        }
    }
}
