//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TN_TeacherUpdate_WebService
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:microsoft-dynamics-schemas/page/tn_teacherupdate", ConfigurationName="TN_TeacherUpdate_WebService.TN_TeacherUpdate_Service")]
    public interface TN_TeacherUpdate_Service
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/tn_teacherupdate:Read", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<TN_TeacherUpdate_WebService.ReadResponse> ReadAsync(TN_TeacherUpdate_WebService.ReadRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/tn_teacherupdate:ReadByRecId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<TN_TeacherUpdate_WebService.ReadByRecIdResponse> ReadByRecIdAsync(TN_TeacherUpdate_WebService.ReadByRecIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/tn_teacherupdate:ReadMultiple", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<TN_TeacherUpdate_WebService.ReadMultipleResponse> ReadMultipleAsync(TN_TeacherUpdate_WebService.ReadMultipleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/tn_teacherupdate:IsUpdated", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<TN_TeacherUpdate_WebService.IsUpdatedResponse> IsUpdatedAsync(TN_TeacherUpdate_WebService.IsUpdatedRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/tn_teacherupdate:GetRecIdFromKey", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<TN_TeacherUpdate_WebService.GetRecIdFromKeyResponse> GetRecIdFromKeyAsync(TN_TeacherUpdate_WebService.GetRecIdFromKeyRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/tn_teacherupdate:Update", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<TN_TeacherUpdate_WebService.UpdateResponse> UpdateAsync(TN_TeacherUpdate_WebService.UpdateRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/tn_teacherupdate:UpdateMultiple", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<TN_TeacherUpdate_WebService.UpdateMultipleResponse> UpdateMultipleAsync(TN_TeacherUpdate_WebService.UpdateMultipleRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/tn_teacherupdate")]
    public partial class TN_TeacherUpdate
    {
        
        private string keyField;
        
        private string noField;
        
        private string first_NameField;
        
        private string sur_NameField;
        
        private string addressField;
        
        private string address_2Field;
        
        private string post_CodeField;
        
        private string cityField;
        
        private string bank_Branch_NoField;
        
        private string bank_Account_NoField;
        
        private string work_Phone_NoField;
        
        private bool work_Phone_Portal_AvailableField;
        
        private bool work_Phone_Portal_AvailableFieldSpecified;
        
        private string work_E_MailField;
        
        private bool work_E_Mail_Portal_AvailableField;
        
        private bool work_E_Mail_Portal_AvailableFieldSpecified;
        
        private bool access_Teacher_NetField;
        
        private bool access_Teacher_NetFieldSpecified;
        
        private string social_Security_NoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Key
        {
            get
            {
                return this.keyField;
            }
            set
            {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string No
        {
            get
            {
                return this.noField;
            }
            set
            {
                this.noField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string First_Name
        {
            get
            {
                return this.first_NameField;
            }
            set
            {
                this.first_NameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Sur_Name
        {
            get
            {
                return this.sur_NameField;
            }
            set
            {
                this.sur_NameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Address
        {
            get
            {
                return this.addressField;
            }
            set
            {
                this.addressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Address_2
        {
            get
            {
                return this.address_2Field;
            }
            set
            {
                this.address_2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Post_Code
        {
            get
            {
                return this.post_CodeField;
            }
            set
            {
                this.post_CodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string City
        {
            get
            {
                return this.cityField;
            }
            set
            {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string Bank_Branch_No
        {
            get
            {
                return this.bank_Branch_NoField;
            }
            set
            {
                this.bank_Branch_NoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string Bank_Account_No
        {
            get
            {
                return this.bank_Account_NoField;
            }
            set
            {
                this.bank_Account_NoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string Work_Phone_No
        {
            get
            {
                return this.work_Phone_NoField;
            }
            set
            {
                this.work_Phone_NoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public bool Work_Phone_Portal_Available
        {
            get
            {
                return this.work_Phone_Portal_AvailableField;
            }
            set
            {
                this.work_Phone_Portal_AvailableField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Work_Phone_Portal_AvailableSpecified
        {
            get
            {
                return this.work_Phone_Portal_AvailableFieldSpecified;
            }
            set
            {
                this.work_Phone_Portal_AvailableFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string Work_E_Mail
        {
            get
            {
                return this.work_E_MailField;
            }
            set
            {
                this.work_E_MailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public bool Work_E_Mail_Portal_Available
        {
            get
            {
                return this.work_E_Mail_Portal_AvailableField;
            }
            set
            {
                this.work_E_Mail_Portal_AvailableField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Work_E_Mail_Portal_AvailableSpecified
        {
            get
            {
                return this.work_E_Mail_Portal_AvailableFieldSpecified;
            }
            set
            {
                this.work_E_Mail_Portal_AvailableFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public bool Access_Teacher_Net
        {
            get
            {
                return this.access_Teacher_NetField;
            }
            set
            {
                this.access_Teacher_NetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Access_Teacher_NetSpecified
        {
            get
            {
                return this.access_Teacher_NetFieldSpecified;
            }
            set
            {
                this.access_Teacher_NetFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string Social_Security_No
        {
            get
            {
                return this.social_Security_NoField;
            }
            set
            {
                this.social_Security_NoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/tn_teacherupdate")]
    public partial class TN_TeacherUpdate_Filter
    {
        
        private TN_TeacherUpdate_Fields fieldField;
        
        private string criteriaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public TN_TeacherUpdate_Fields Field
        {
            get
            {
                return this.fieldField;
            }
            set
            {
                this.fieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Criteria
        {
            get
            {
                return this.criteriaField;
            }
            set
            {
                this.criteriaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/tn_teacherupdate")]
    public enum TN_TeacherUpdate_Fields
    {
        
        /// <remarks/>
        No,
        
        /// <remarks/>
        First_Name,
        
        /// <remarks/>
        Sur_Name,
        
        /// <remarks/>
        Address,
        
        /// <remarks/>
        Address_2,
        
        /// <remarks/>
        Post_Code,
        
        /// <remarks/>
        City,
        
        /// <remarks/>
        Bank_Branch_No,
        
        /// <remarks/>
        Bank_Account_No,
        
        /// <remarks/>
        Work_Phone_No,
        
        /// <remarks/>
        Work_Phone_Portal_Available,
        
        /// <remarks/>
        Work_E_Mail,
        
        /// <remarks/>
        Work_E_Mail_Portal_Available,
        
        /// <remarks/>
        Access_Teacher_Net,
        
        /// <remarks/>
        Social_Security_No,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Read", WrapperNamespace="urn:microsoft-dynamics-schemas/page/tn_teacherupdate", IsWrapped=true)]
    public partial class ReadRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/tn_teacherupdate", Order=0)]
        public string No;
        
        public ReadRequest()
        {
        }
        
        public ReadRequest(string No)
        {
            this.No = No;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Read_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/tn_teacherupdate", IsWrapped=true)]
    public partial class ReadResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/tn_teacherupdate", Order=0)]
        public TN_TeacherUpdate_WebService.TN_TeacherUpdate TN_TeacherUpdate;
        
        public ReadResponse()
        {
        }
        
        public ReadResponse(TN_TeacherUpdate_WebService.TN_TeacherUpdate TN_TeacherUpdate)
        {
            this.TN_TeacherUpdate = TN_TeacherUpdate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadByRecId", WrapperNamespace="urn:microsoft-dynamics-schemas/page/tn_teacherupdate", IsWrapped=true)]
    public partial class ReadByRecIdRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/tn_teacherupdate", Order=0)]
        public string recId;
        
        public ReadByRecIdRequest()
        {
        }
        
        public ReadByRecIdRequest(string recId)
        {
            this.recId = recId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadByRecId_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/tn_teacherupdate", IsWrapped=true)]
    public partial class ReadByRecIdResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/tn_teacherupdate", Order=0)]
        public TN_TeacherUpdate_WebService.TN_TeacherUpdate TN_TeacherUpdate;
        
        public ReadByRecIdResponse()
        {
        }
        
        public ReadByRecIdResponse(TN_TeacherUpdate_WebService.TN_TeacherUpdate TN_TeacherUpdate)
        {
            this.TN_TeacherUpdate = TN_TeacherUpdate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadMultiple", WrapperNamespace="urn:microsoft-dynamics-schemas/page/tn_teacherupdate", IsWrapped=true)]
    public partial class ReadMultipleRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/tn_teacherupdate", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("filter")]
        public TN_TeacherUpdate_WebService.TN_TeacherUpdate_Filter[] filter;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/tn_teacherupdate", Order=1)]
        public string bookmarkKey;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/tn_teacherupdate", Order=2)]
        public int setSize;
        
        public ReadMultipleRequest()
        {
        }
        
        public ReadMultipleRequest(TN_TeacherUpdate_WebService.TN_TeacherUpdate_Filter[] filter, string bookmarkKey, int setSize)
        {
            this.filter = filter;
            this.bookmarkKey = bookmarkKey;
            this.setSize = setSize;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadMultiple_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/tn_teacherupdate", IsWrapped=true)]
    public partial class ReadMultipleResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/tn_teacherupdate", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public TN_TeacherUpdate_WebService.TN_TeacherUpdate[] ReadMultiple_Result;
        
        public ReadMultipleResponse()
        {
        }
        
        public ReadMultipleResponse(TN_TeacherUpdate_WebService.TN_TeacherUpdate[] ReadMultiple_Result)
        {
            this.ReadMultiple_Result = ReadMultiple_Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IsUpdated", WrapperNamespace="urn:microsoft-dynamics-schemas/page/tn_teacherupdate", IsWrapped=true)]
    public partial class IsUpdatedRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/tn_teacherupdate", Order=0)]
        public string Key;
        
        public IsUpdatedRequest()
        {
        }
        
        public IsUpdatedRequest(string Key)
        {
            this.Key = Key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IsUpdated_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/tn_teacherupdate", IsWrapped=true)]
    public partial class IsUpdatedResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/tn_teacherupdate", Order=0)]
        public bool IsUpdated_Result;
        
        public IsUpdatedResponse()
        {
        }
        
        public IsUpdatedResponse(bool IsUpdated_Result)
        {
            this.IsUpdated_Result = IsUpdated_Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetRecIdFromKey", WrapperNamespace="urn:microsoft-dynamics-schemas/page/tn_teacherupdate", IsWrapped=true)]
    public partial class GetRecIdFromKeyRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/tn_teacherupdate", Order=0)]
        public string Key;
        
        public GetRecIdFromKeyRequest()
        {
        }
        
        public GetRecIdFromKeyRequest(string Key)
        {
            this.Key = Key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetRecIdFromKey_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/tn_teacherupdate", IsWrapped=true)]
    public partial class GetRecIdFromKeyResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/tn_teacherupdate", Order=0)]
        public string GetRecIdFromKey_Result;
        
        public GetRecIdFromKeyResponse()
        {
        }
        
        public GetRecIdFromKeyResponse(string GetRecIdFromKey_Result)
        {
            this.GetRecIdFromKey_Result = GetRecIdFromKey_Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Update", WrapperNamespace="urn:microsoft-dynamics-schemas/page/tn_teacherupdate", IsWrapped=true)]
    public partial class UpdateRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/tn_teacherupdate", Order=0)]
        public TN_TeacherUpdate_WebService.TN_TeacherUpdate TN_TeacherUpdate;
        
        public UpdateRequest()
        {
        }
        
        public UpdateRequest(TN_TeacherUpdate_WebService.TN_TeacherUpdate TN_TeacherUpdate)
        {
            this.TN_TeacherUpdate = TN_TeacherUpdate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Update_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/tn_teacherupdate", IsWrapped=true)]
    public partial class UpdateResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/tn_teacherupdate", Order=0)]
        public TN_TeacherUpdate_WebService.TN_TeacherUpdate TN_TeacherUpdate;
        
        public UpdateResponse()
        {
        }
        
        public UpdateResponse(TN_TeacherUpdate_WebService.TN_TeacherUpdate TN_TeacherUpdate)
        {
            this.TN_TeacherUpdate = TN_TeacherUpdate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateMultiple", WrapperNamespace="urn:microsoft-dynamics-schemas/page/tn_teacherupdate", IsWrapped=true)]
    public partial class UpdateMultipleRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/tn_teacherupdate", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public TN_TeacherUpdate_WebService.TN_TeacherUpdate[] TN_TeacherUpdate_List;
        
        public UpdateMultipleRequest()
        {
        }
        
        public UpdateMultipleRequest(TN_TeacherUpdate_WebService.TN_TeacherUpdate[] TN_TeacherUpdate_List)
        {
            this.TN_TeacherUpdate_List = TN_TeacherUpdate_List;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateMultiple_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/tn_teacherupdate", IsWrapped=true)]
    public partial class UpdateMultipleResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/tn_teacherupdate", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public TN_TeacherUpdate_WebService.TN_TeacherUpdate[] TN_TeacherUpdate_List;
        
        public UpdateMultipleResponse()
        {
        }
        
        public UpdateMultipleResponse(TN_TeacherUpdate_WebService.TN_TeacherUpdate[] TN_TeacherUpdate_List)
        {
            this.TN_TeacherUpdate_List = TN_TeacherUpdate_List;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface TN_TeacherUpdate_ServiceChannel : TN_TeacherUpdate_WebService.TN_TeacherUpdate_Service, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class TN_TeacherUpdate_ServiceClient : System.ServiceModel.ClientBase<TN_TeacherUpdate_WebService.TN_TeacherUpdate_Service>, TN_TeacherUpdate_WebService.TN_TeacherUpdate_Service
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public TN_TeacherUpdate_ServiceClient() : 
                base(TN_TeacherUpdate_ServiceClient.GetDefaultBinding(), TN_TeacherUpdate_ServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.TN_TeacherUpdate_Service.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TN_TeacherUpdate_ServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(TN_TeacherUpdate_ServiceClient.GetBindingForEndpoint(endpointConfiguration), TN_TeacherUpdate_ServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TN_TeacherUpdate_ServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(TN_TeacherUpdate_ServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TN_TeacherUpdate_ServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(TN_TeacherUpdate_ServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TN_TeacherUpdate_ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TN_TeacherUpdate_WebService.ReadResponse> TN_TeacherUpdate_WebService.TN_TeacherUpdate_Service.ReadAsync(TN_TeacherUpdate_WebService.ReadRequest request)
        {
            return base.Channel.ReadAsync(request);
        }
        
        public System.Threading.Tasks.Task<TN_TeacherUpdate_WebService.ReadResponse> ReadAsync(string No)
        {
            TN_TeacherUpdate_WebService.ReadRequest inValue = new TN_TeacherUpdate_WebService.ReadRequest();
            inValue.No = No;
            return ((TN_TeacherUpdate_WebService.TN_TeacherUpdate_Service)(this)).ReadAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TN_TeacherUpdate_WebService.ReadByRecIdResponse> TN_TeacherUpdate_WebService.TN_TeacherUpdate_Service.ReadByRecIdAsync(TN_TeacherUpdate_WebService.ReadByRecIdRequest request)
        {
            return base.Channel.ReadByRecIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<TN_TeacherUpdate_WebService.ReadByRecIdResponse> ReadByRecIdAsync(string recId)
        {
            TN_TeacherUpdate_WebService.ReadByRecIdRequest inValue = new TN_TeacherUpdate_WebService.ReadByRecIdRequest();
            inValue.recId = recId;
            return ((TN_TeacherUpdate_WebService.TN_TeacherUpdate_Service)(this)).ReadByRecIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TN_TeacherUpdate_WebService.ReadMultipleResponse> TN_TeacherUpdate_WebService.TN_TeacherUpdate_Service.ReadMultipleAsync(TN_TeacherUpdate_WebService.ReadMultipleRequest request)
        {
            return base.Channel.ReadMultipleAsync(request);
        }
        
        public System.Threading.Tasks.Task<TN_TeacherUpdate_WebService.ReadMultipleResponse> ReadMultipleAsync(TN_TeacherUpdate_WebService.TN_TeacherUpdate_Filter[] filter, string bookmarkKey, int setSize)
        {
            TN_TeacherUpdate_WebService.ReadMultipleRequest inValue = new TN_TeacherUpdate_WebService.ReadMultipleRequest();
            inValue.filter = filter;
            inValue.bookmarkKey = bookmarkKey;
            inValue.setSize = setSize;
            return ((TN_TeacherUpdate_WebService.TN_TeacherUpdate_Service)(this)).ReadMultipleAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TN_TeacherUpdate_WebService.IsUpdatedResponse> TN_TeacherUpdate_WebService.TN_TeacherUpdate_Service.IsUpdatedAsync(TN_TeacherUpdate_WebService.IsUpdatedRequest request)
        {
            return base.Channel.IsUpdatedAsync(request);
        }
        
        public System.Threading.Tasks.Task<TN_TeacherUpdate_WebService.IsUpdatedResponse> IsUpdatedAsync(string Key)
        {
            TN_TeacherUpdate_WebService.IsUpdatedRequest inValue = new TN_TeacherUpdate_WebService.IsUpdatedRequest();
            inValue.Key = Key;
            return ((TN_TeacherUpdate_WebService.TN_TeacherUpdate_Service)(this)).IsUpdatedAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TN_TeacherUpdate_WebService.GetRecIdFromKeyResponse> TN_TeacherUpdate_WebService.TN_TeacherUpdate_Service.GetRecIdFromKeyAsync(TN_TeacherUpdate_WebService.GetRecIdFromKeyRequest request)
        {
            return base.Channel.GetRecIdFromKeyAsync(request);
        }
        
        public System.Threading.Tasks.Task<TN_TeacherUpdate_WebService.GetRecIdFromKeyResponse> GetRecIdFromKeyAsync(string Key)
        {
            TN_TeacherUpdate_WebService.GetRecIdFromKeyRequest inValue = new TN_TeacherUpdate_WebService.GetRecIdFromKeyRequest();
            inValue.Key = Key;
            return ((TN_TeacherUpdate_WebService.TN_TeacherUpdate_Service)(this)).GetRecIdFromKeyAsync(inValue);
        }
        
        public System.Threading.Tasks.Task<TN_TeacherUpdate_WebService.UpdateResponse> UpdateAsync(TN_TeacherUpdate_WebService.UpdateRequest request)
        {
            return base.Channel.UpdateAsync(request);
        }
        
        public System.Threading.Tasks.Task<TN_TeacherUpdate_WebService.UpdateMultipleResponse> UpdateMultipleAsync(TN_TeacherUpdate_WebService.UpdateMultipleRequest request)
        {
            return base.Channel.UpdateMultipleAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.TN_TeacherUpdate_Service))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.TN_TeacherUpdate_Service))
            {
                return new System.ServiceModel.EndpointAddress("https://iqiapimanagement-asa-dev.azure-api.net/tn_teacherupdate");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return TN_TeacherUpdate_ServiceClient.GetBindingForEndpoint(EndpointConfiguration.TN_TeacherUpdate_Service);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return TN_TeacherUpdate_ServiceClient.GetEndpointAddress(EndpointConfiguration.TN_TeacherUpdate_Service);
        }
        
        public enum EndpointConfiguration
        {
            
            TN_TeacherUpdate_Service,
        }
    }
}
