//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseTeacherReport_WebService
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:microsoft-dynamics-schemas/page/courseteacherreport", ConfigurationName="CourseTeacherReport_WebService.CourseTeacherReport_Service")]
    public interface CourseTeacherReport_Service
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/courseteacherreport:Read", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<CourseTeacherReport_WebService.ReadResponse> ReadAsync(CourseTeacherReport_WebService.ReadRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/courseteacherreport:ReadByRecId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<CourseTeacherReport_WebService.ReadByRecIdResponse> ReadByRecIdAsync(CourseTeacherReport_WebService.ReadByRecIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/courseteacherreport:ReadMultiple", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<CourseTeacherReport_WebService.ReadMultipleResponse> ReadMultipleAsync(CourseTeacherReport_WebService.ReadMultipleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/courseteacherreport:IsUpdated", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<CourseTeacherReport_WebService.IsUpdatedResponse> IsUpdatedAsync(CourseTeacherReport_WebService.IsUpdatedRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/courseteacherreport:GetRecIdFromKey", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<CourseTeacherReport_WebService.GetRecIdFromKeyResponse> GetRecIdFromKeyAsync(CourseTeacherReport_WebService.GetRecIdFromKeyRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/courseteacherreport:GenTeacherReport", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<CourseTeacherReport_WebService.GenTeacherReportResponse> GenTeacherReportAsync(CourseTeacherReport_WebService.GenTeacherReportRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/courseteacherreport")]
    public partial class CourseTeacherReport
    {
        
        private string keyField;
        
        private string course_Header_NoField;
        
        private string descriptionField;
        
        private string course_TypeField;
        
        private Course_Header_Status course_Header_StatusField;
        
        private bool course_Header_StatusFieldSpecified;
        
        private string teacher_NoField;
        
        private string teacher_NameField;
        
        private bool primary_TeacherField;
        
        private bool primary_TeacherFieldSpecified;
        
        private decimal qty_Meeting_TimesField;
        
        private bool qty_Meeting_TimesFieldSpecified;
        
        private decimal qty_LessonsField;
        
        private bool qty_LessonsFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Key
        {
            get
            {
                return this.keyField;
            }
            set
            {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Course_Header_No
        {
            get
            {
                return this.course_Header_NoField;
            }
            set
            {
                this.course_Header_NoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Course_Type
        {
            get
            {
                return this.course_TypeField;
            }
            set
            {
                this.course_TypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public Course_Header_Status Course_Header_Status
        {
            get
            {
                return this.course_Header_StatusField;
            }
            set
            {
                this.course_Header_StatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Course_Header_StatusSpecified
        {
            get
            {
                return this.course_Header_StatusFieldSpecified;
            }
            set
            {
                this.course_Header_StatusFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Teacher_No
        {
            get
            {
                return this.teacher_NoField;
            }
            set
            {
                this.teacher_NoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Teacher_Name
        {
            get
            {
                return this.teacher_NameField;
            }
            set
            {
                this.teacher_NameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public bool Primary_Teacher
        {
            get
            {
                return this.primary_TeacherField;
            }
            set
            {
                this.primary_TeacherField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Primary_TeacherSpecified
        {
            get
            {
                return this.primary_TeacherFieldSpecified;
            }
            set
            {
                this.primary_TeacherFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public decimal Qty_Meeting_Times
        {
            get
            {
                return this.qty_Meeting_TimesField;
            }
            set
            {
                this.qty_Meeting_TimesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Qty_Meeting_TimesSpecified
        {
            get
            {
                return this.qty_Meeting_TimesFieldSpecified;
            }
            set
            {
                this.qty_Meeting_TimesFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public decimal Qty_Lessons
        {
            get
            {
                return this.qty_LessonsField;
            }
            set
            {
                this.qty_LessonsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Qty_LessonsSpecified
        {
            get
            {
                return this.qty_LessonsFieldSpecified;
            }
            set
            {
                this.qty_LessonsFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/courseteacherreport")]
    public enum Course_Header_Status
    {
        
        /// <remarks/>
        Planning,
        
        /// <remarks/>
        booked,
        
        /// <remarks/>
        Cancelled,
        
        /// <remarks/>
        Completed,
        
        /// <remarks/>
        Launched,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/courseteacherreport")]
    public partial class CourseTeacherReport_Filter
    {
        
        private CourseTeacherReport_Fields fieldField;
        
        private string criteriaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public CourseTeacherReport_Fields Field
        {
            get
            {
                return this.fieldField;
            }
            set
            {
                this.fieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Criteria
        {
            get
            {
                return this.criteriaField;
            }
            set
            {
                this.criteriaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/courseteacherreport")]
    public enum CourseTeacherReport_Fields
    {
        
        /// <remarks/>
        Course_Header_No,
        
        /// <remarks/>
        Description,
        
        /// <remarks/>
        Course_Type,
        
        /// <remarks/>
        Course_Header_Status,
        
        /// <remarks/>
        Teacher_No,
        
        /// <remarks/>
        Teacher_Name,
        
        /// <remarks/>
        Primary_Teacher,
        
        /// <remarks/>
        Qty_Meeting_Times,
        
        /// <remarks/>
        Qty_Lessons,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Read", WrapperNamespace="urn:microsoft-dynamics-schemas/page/courseteacherreport", IsWrapped=true)]
    public partial class ReadRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/courseteacherreport", Order=0)]
        public string Course_Header_No;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/courseteacherreport", Order=1)]
        public string Teacher_No;
        
        public ReadRequest()
        {
        }
        
        public ReadRequest(string Course_Header_No, string Teacher_No)
        {
            this.Course_Header_No = Course_Header_No;
            this.Teacher_No = Teacher_No;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Read_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/courseteacherreport", IsWrapped=true)]
    public partial class ReadResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/courseteacherreport", Order=0)]
        public CourseTeacherReport_WebService.CourseTeacherReport CourseTeacherReport;
        
        public ReadResponse()
        {
        }
        
        public ReadResponse(CourseTeacherReport_WebService.CourseTeacherReport CourseTeacherReport)
        {
            this.CourseTeacherReport = CourseTeacherReport;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadByRecId", WrapperNamespace="urn:microsoft-dynamics-schemas/page/courseteacherreport", IsWrapped=true)]
    public partial class ReadByRecIdRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/courseteacherreport", Order=0)]
        public string recId;
        
        public ReadByRecIdRequest()
        {
        }
        
        public ReadByRecIdRequest(string recId)
        {
            this.recId = recId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadByRecId_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/courseteacherreport", IsWrapped=true)]
    public partial class ReadByRecIdResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/courseteacherreport", Order=0)]
        public CourseTeacherReport_WebService.CourseTeacherReport CourseTeacherReport;
        
        public ReadByRecIdResponse()
        {
        }
        
        public ReadByRecIdResponse(CourseTeacherReport_WebService.CourseTeacherReport CourseTeacherReport)
        {
            this.CourseTeacherReport = CourseTeacherReport;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadMultiple", WrapperNamespace="urn:microsoft-dynamics-schemas/page/courseteacherreport", IsWrapped=true)]
    public partial class ReadMultipleRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/courseteacherreport", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("filter")]
        public CourseTeacherReport_WebService.CourseTeacherReport_Filter[] filter;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/courseteacherreport", Order=1)]
        public string bookmarkKey;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/courseteacherreport", Order=2)]
        public int setSize;
        
        public ReadMultipleRequest()
        {
        }
        
        public ReadMultipleRequest(CourseTeacherReport_WebService.CourseTeacherReport_Filter[] filter, string bookmarkKey, int setSize)
        {
            this.filter = filter;
            this.bookmarkKey = bookmarkKey;
            this.setSize = setSize;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadMultiple_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/courseteacherreport", IsWrapped=true)]
    public partial class ReadMultipleResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/courseteacherreport", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public CourseTeacherReport_WebService.CourseTeacherReport[] ReadMultiple_Result;
        
        public ReadMultipleResponse()
        {
        }
        
        public ReadMultipleResponse(CourseTeacherReport_WebService.CourseTeacherReport[] ReadMultiple_Result)
        {
            this.ReadMultiple_Result = ReadMultiple_Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IsUpdated", WrapperNamespace="urn:microsoft-dynamics-schemas/page/courseteacherreport", IsWrapped=true)]
    public partial class IsUpdatedRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/courseteacherreport", Order=0)]
        public string Key;
        
        public IsUpdatedRequest()
        {
        }
        
        public IsUpdatedRequest(string Key)
        {
            this.Key = Key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IsUpdated_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/courseteacherreport", IsWrapped=true)]
    public partial class IsUpdatedResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/courseteacherreport", Order=0)]
        public bool IsUpdated_Result;
        
        public IsUpdatedResponse()
        {
        }
        
        public IsUpdatedResponse(bool IsUpdated_Result)
        {
            this.IsUpdated_Result = IsUpdated_Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetRecIdFromKey", WrapperNamespace="urn:microsoft-dynamics-schemas/page/courseteacherreport", IsWrapped=true)]
    public partial class GetRecIdFromKeyRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/courseteacherreport", Order=0)]
        public string Key;
        
        public GetRecIdFromKeyRequest()
        {
        }
        
        public GetRecIdFromKeyRequest(string Key)
        {
            this.Key = Key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetRecIdFromKey_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/courseteacherreport", IsWrapped=true)]
    public partial class GetRecIdFromKeyResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/courseteacherreport", Order=0)]
        public string GetRecIdFromKey_Result;
        
        public GetRecIdFromKeyResponse()
        {
        }
        
        public GetRecIdFromKeyResponse(string GetRecIdFromKey_Result)
        {
            this.GetRecIdFromKey_Result = GetRecIdFromKey_Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GenTeacherReport", WrapperNamespace="urn:microsoft-dynamics-schemas/page/courseteacherreport", IsWrapped=true)]
    public partial class GenTeacherReportRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/courseteacherreport", Order=0)]
        public string courseTeacher;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/courseteacherreport", Order=1)]
        public int reportDef;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/courseteacherreport", Order=2)]
        public string bin64String;
        
        public GenTeacherReportRequest()
        {
        }
        
        public GenTeacherReportRequest(string courseTeacher, int reportDef, string bin64String)
        {
            this.courseTeacher = courseTeacher;
            this.reportDef = reportDef;
            this.bin64String = bin64String;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GenTeacherReport_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/courseteacherreport", IsWrapped=true)]
    public partial class GenTeacherReportResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/courseteacherreport", Order=0)]
        public string return_value;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/courseteacherreport", Order=1)]
        public string bin64String;
        
        public GenTeacherReportResponse()
        {
        }
        
        public GenTeacherReportResponse(string return_value, string bin64String)
        {
            this.return_value = return_value;
            this.bin64String = bin64String;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface CourseTeacherReport_ServiceChannel : CourseTeacherReport_WebService.CourseTeacherReport_Service, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class CourseTeacherReport_ServiceClient : System.ServiceModel.ClientBase<CourseTeacherReport_WebService.CourseTeacherReport_Service>, CourseTeacherReport_WebService.CourseTeacherReport_Service
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public CourseTeacherReport_ServiceClient() : 
                base(CourseTeacherReport_ServiceClient.GetDefaultBinding(), CourseTeacherReport_ServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.CourseTeacherReport_Service.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CourseTeacherReport_ServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(CourseTeacherReport_ServiceClient.GetBindingForEndpoint(endpointConfiguration), CourseTeacherReport_ServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CourseTeacherReport_ServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(CourseTeacherReport_ServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CourseTeacherReport_ServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(CourseTeacherReport_ServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CourseTeacherReport_ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CourseTeacherReport_WebService.ReadResponse> CourseTeacherReport_WebService.CourseTeacherReport_Service.ReadAsync(CourseTeacherReport_WebService.ReadRequest request)
        {
            return base.Channel.ReadAsync(request);
        }
        
        public System.Threading.Tasks.Task<CourseTeacherReport_WebService.ReadResponse> ReadAsync(string Course_Header_No, string Teacher_No)
        {
            CourseTeacherReport_WebService.ReadRequest inValue = new CourseTeacherReport_WebService.ReadRequest();
            inValue.Course_Header_No = Course_Header_No;
            inValue.Teacher_No = Teacher_No;
            return ((CourseTeacherReport_WebService.CourseTeacherReport_Service)(this)).ReadAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CourseTeacherReport_WebService.ReadByRecIdResponse> CourseTeacherReport_WebService.CourseTeacherReport_Service.ReadByRecIdAsync(CourseTeacherReport_WebService.ReadByRecIdRequest request)
        {
            return base.Channel.ReadByRecIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<CourseTeacherReport_WebService.ReadByRecIdResponse> ReadByRecIdAsync(string recId)
        {
            CourseTeacherReport_WebService.ReadByRecIdRequest inValue = new CourseTeacherReport_WebService.ReadByRecIdRequest();
            inValue.recId = recId;
            return ((CourseTeacherReport_WebService.CourseTeacherReport_Service)(this)).ReadByRecIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CourseTeacherReport_WebService.ReadMultipleResponse> CourseTeacherReport_WebService.CourseTeacherReport_Service.ReadMultipleAsync(CourseTeacherReport_WebService.ReadMultipleRequest request)
        {
            return base.Channel.ReadMultipleAsync(request);
        }
        
        public System.Threading.Tasks.Task<CourseTeacherReport_WebService.ReadMultipleResponse> ReadMultipleAsync(CourseTeacherReport_WebService.CourseTeacherReport_Filter[] filter, string bookmarkKey, int setSize)
        {
            CourseTeacherReport_WebService.ReadMultipleRequest inValue = new CourseTeacherReport_WebService.ReadMultipleRequest();
            inValue.filter = filter;
            inValue.bookmarkKey = bookmarkKey;
            inValue.setSize = setSize;
            return ((CourseTeacherReport_WebService.CourseTeacherReport_Service)(this)).ReadMultipleAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CourseTeacherReport_WebService.IsUpdatedResponse> CourseTeacherReport_WebService.CourseTeacherReport_Service.IsUpdatedAsync(CourseTeacherReport_WebService.IsUpdatedRequest request)
        {
            return base.Channel.IsUpdatedAsync(request);
        }
        
        public System.Threading.Tasks.Task<CourseTeacherReport_WebService.IsUpdatedResponse> IsUpdatedAsync(string Key)
        {
            CourseTeacherReport_WebService.IsUpdatedRequest inValue = new CourseTeacherReport_WebService.IsUpdatedRequest();
            inValue.Key = Key;
            return ((CourseTeacherReport_WebService.CourseTeacherReport_Service)(this)).IsUpdatedAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CourseTeacherReport_WebService.GetRecIdFromKeyResponse> CourseTeacherReport_WebService.CourseTeacherReport_Service.GetRecIdFromKeyAsync(CourseTeacherReport_WebService.GetRecIdFromKeyRequest request)
        {
            return base.Channel.GetRecIdFromKeyAsync(request);
        }
        
        public System.Threading.Tasks.Task<CourseTeacherReport_WebService.GetRecIdFromKeyResponse> GetRecIdFromKeyAsync(string Key)
        {
            CourseTeacherReport_WebService.GetRecIdFromKeyRequest inValue = new CourseTeacherReport_WebService.GetRecIdFromKeyRequest();
            inValue.Key = Key;
            return ((CourseTeacherReport_WebService.CourseTeacherReport_Service)(this)).GetRecIdFromKeyAsync(inValue);
        }
        
        public System.Threading.Tasks.Task<CourseTeacherReport_WebService.GenTeacherReportResponse> GenTeacherReportAsync(CourseTeacherReport_WebService.GenTeacherReportRequest request)
        {
            return base.Channel.GenTeacherReportAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.CourseTeacherReport_Service))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.CourseTeacherReport_Service))
            {
                return new System.ServiceModel.EndpointAddress("https://iqiapimanagement-asa-dev.azure-api.net/courseteacherreport");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return CourseTeacherReport_ServiceClient.GetBindingForEndpoint(EndpointConfiguration.CourseTeacherReport_Service);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return CourseTeacherReport_ServiceClient.GetEndpointAddress(EndpointConfiguration.CourseTeacherReport_Service);
        }
        
        public enum EndpointConfiguration
        {
            
            CourseTeacherReport_Service,
        }
    }
}
