//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseLocationList_WebService
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:microsoft-dynamics-schemas/page/courselocationlist", ConfigurationName="CourseLocationList_WebService.CourseLocationList_Service")]
    public interface CourseLocationList_Service
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/courselocationlist:Read", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<CourseLocationList_WebService.ReadResponse> ReadAsync(CourseLocationList_WebService.ReadRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/courselocationlist:ReadByRecId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<CourseLocationList_WebService.ReadByRecIdResponse> ReadByRecIdAsync(CourseLocationList_WebService.ReadByRecIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/courselocationlist:ReadMultiple", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<CourseLocationList_WebService.ReadMultipleResponse> ReadMultipleAsync(CourseLocationList_WebService.ReadMultipleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/courselocationlist:IsUpdated", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<CourseLocationList_WebService.IsUpdatedResponse> IsUpdatedAsync(CourseLocationList_WebService.IsUpdatedRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/courselocationlist:GetRecIdFromKey", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<CourseLocationList_WebService.GetRecIdFromKeyResponse> GetRecIdFromKeyAsync(CourseLocationList_WebService.GetRecIdFromKeyRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/courselocationlist")]
    public partial class courseLocationList
    {
        
        private string keyField;
        
        private string noField;
        
        private string nameField;
        
        private string search_NameField;
        
        private string name_2Field;
        
        private string addressField;
        
        private string address_2Field;
        
        private string post_CodeField;
        
        private string cityField;
        
        private string phone_NoField;
        
        private string country_Region_CodeField;
        
        private string county_DescriptionField;
        
        private string countyField;
        
        private int quantity_Class_RoomsField;
        
        private bool quantity_Class_RoomsFieldSpecified;
        
        private bool commentField;
        
        private bool commentFieldSpecified;
        
        private string e_MailField;
        
        private string home_PageField;
        
        private string no_SeriesField;
        
        private string municipal_CodeField;
        
        private string municipal_NameField;
        
        private bool blockedField;
        
        private bool blockedFieldSpecified;
        
        private string contact_Person_NoField;
        
        private decimal priceField;
        
        private bool priceFieldSpecified;
        
        private string unit_of_MeasureField;
        
        private decimal subsidies_per_LessonField;
        
        private bool subsidies_per_LessonFieldSpecified;
        
        private decimal latitudeField;
        
        private bool latitudeFieldSpecified;
        
        private decimal longitudeField;
        
        private bool longitudeFieldSpecified;
        
        private bool descriptionField;
        
        private bool descriptionFieldSpecified;
        
        private string contact_First_NameField;
        
        private string contact_Sur_NameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Key
        {
            get
            {
                return this.keyField;
            }
            set
            {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string No
        {
            get
            {
                return this.noField;
            }
            set
            {
                this.noField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Search_Name
        {
            get
            {
                return this.search_NameField;
            }
            set
            {
                this.search_NameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Name_2
        {
            get
            {
                return this.name_2Field;
            }
            set
            {
                this.name_2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Address
        {
            get
            {
                return this.addressField;
            }
            set
            {
                this.addressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Address_2
        {
            get
            {
                return this.address_2Field;
            }
            set
            {
                this.address_2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Post_Code
        {
            get
            {
                return this.post_CodeField;
            }
            set
            {
                this.post_CodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string City
        {
            get
            {
                return this.cityField;
            }
            set
            {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string Phone_No
        {
            get
            {
                return this.phone_NoField;
            }
            set
            {
                this.phone_NoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string Country_Region_Code
        {
            get
            {
                return this.country_Region_CodeField;
            }
            set
            {
                this.country_Region_CodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string County_Description
        {
            get
            {
                return this.county_DescriptionField;
            }
            set
            {
                this.county_DescriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string County
        {
            get
            {
                return this.countyField;
            }
            set
            {
                this.countyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public int Quantity_Class_Rooms
        {
            get
            {
                return this.quantity_Class_RoomsField;
            }
            set
            {
                this.quantity_Class_RoomsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Quantity_Class_RoomsSpecified
        {
            get
            {
                return this.quantity_Class_RoomsFieldSpecified;
            }
            set
            {
                this.quantity_Class_RoomsFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public bool Comment
        {
            get
            {
                return this.commentField;
            }
            set
            {
                this.commentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CommentSpecified
        {
            get
            {
                return this.commentFieldSpecified;
            }
            set
            {
                this.commentFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string E_Mail
        {
            get
            {
                return this.e_MailField;
            }
            set
            {
                this.e_MailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string Home_Page
        {
            get
            {
                return this.home_PageField;
            }
            set
            {
                this.home_PageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string No_Series
        {
            get
            {
                return this.no_SeriesField;
            }
            set
            {
                this.no_SeriesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string Municipal_Code
        {
            get
            {
                return this.municipal_CodeField;
            }
            set
            {
                this.municipal_CodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string Municipal_Name
        {
            get
            {
                return this.municipal_NameField;
            }
            set
            {
                this.municipal_NameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public bool Blocked
        {
            get
            {
                return this.blockedField;
            }
            set
            {
                this.blockedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BlockedSpecified
        {
            get
            {
                return this.blockedFieldSpecified;
            }
            set
            {
                this.blockedFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public string Contact_Person_No
        {
            get
            {
                return this.contact_Person_NoField;
            }
            set
            {
                this.contact_Person_NoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public decimal Price
        {
            get
            {
                return this.priceField;
            }
            set
            {
                this.priceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PriceSpecified
        {
            get
            {
                return this.priceFieldSpecified;
            }
            set
            {
                this.priceFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public string Unit_of_Measure
        {
            get
            {
                return this.unit_of_MeasureField;
            }
            set
            {
                this.unit_of_MeasureField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public decimal Subsidies_per_Lesson
        {
            get
            {
                return this.subsidies_per_LessonField;
            }
            set
            {
                this.subsidies_per_LessonField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Subsidies_per_LessonSpecified
        {
            get
            {
                return this.subsidies_per_LessonFieldSpecified;
            }
            set
            {
                this.subsidies_per_LessonFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=25)]
        public decimal Latitude
        {
            get
            {
                return this.latitudeField;
            }
            set
            {
                this.latitudeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LatitudeSpecified
        {
            get
            {
                return this.latitudeFieldSpecified;
            }
            set
            {
                this.latitudeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=26)]
        public decimal Longitude
        {
            get
            {
                return this.longitudeField;
            }
            set
            {
                this.longitudeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LongitudeSpecified
        {
            get
            {
                return this.longitudeFieldSpecified;
            }
            set
            {
                this.longitudeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=27)]
        public bool Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DescriptionSpecified
        {
            get
            {
                return this.descriptionFieldSpecified;
            }
            set
            {
                this.descriptionFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=28)]
        public string Contact_First_Name
        {
            get
            {
                return this.contact_First_NameField;
            }
            set
            {
                this.contact_First_NameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=29)]
        public string Contact_Sur_Name
        {
            get
            {
                return this.contact_Sur_NameField;
            }
            set
            {
                this.contact_Sur_NameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/courselocationlist")]
    public partial class courseLocationList_Filter
    {
        
        private courseLocationList_Fields fieldField;
        
        private string criteriaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public courseLocationList_Fields Field
        {
            get
            {
                return this.fieldField;
            }
            set
            {
                this.fieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Criteria
        {
            get
            {
                return this.criteriaField;
            }
            set
            {
                this.criteriaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/courselocationlist")]
    public enum courseLocationList_Fields
    {
        
        /// <remarks/>
        No,
        
        /// <remarks/>
        Name,
        
        /// <remarks/>
        Search_Name,
        
        /// <remarks/>
        Name_2,
        
        /// <remarks/>
        Address,
        
        /// <remarks/>
        Address_2,
        
        /// <remarks/>
        Post_Code,
        
        /// <remarks/>
        City,
        
        /// <remarks/>
        Phone_No,
        
        /// <remarks/>
        Country_Region_Code,
        
        /// <remarks/>
        County_Description,
        
        /// <remarks/>
        County,
        
        /// <remarks/>
        Quantity_Class_Rooms,
        
        /// <remarks/>
        Comment,
        
        /// <remarks/>
        E_Mail,
        
        /// <remarks/>
        Home_Page,
        
        /// <remarks/>
        No_Series,
        
        /// <remarks/>
        Municipal_Code,
        
        /// <remarks/>
        Municipal_Name,
        
        /// <remarks/>
        Blocked,
        
        /// <remarks/>
        Contact_Person_No,
        
        /// <remarks/>
        Price,
        
        /// <remarks/>
        Unit_of_Measure,
        
        /// <remarks/>
        Subsidies_per_Lesson,
        
        /// <remarks/>
        Latitude,
        
        /// <remarks/>
        Longitude,
        
        /// <remarks/>
        Description,
        
        /// <remarks/>
        Contact_First_Name,
        
        /// <remarks/>
        Contact_Sur_Name,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Read", WrapperNamespace="urn:microsoft-dynamics-schemas/page/courselocationlist", IsWrapped=true)]
    public partial class ReadRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/courselocationlist", Order=0)]
        public string No;
        
        public ReadRequest()
        {
        }
        
        public ReadRequest(string No)
        {
            this.No = No;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Read_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/courselocationlist", IsWrapped=true)]
    public partial class ReadResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/courselocationlist", Order=0)]
        public CourseLocationList_WebService.courseLocationList courseLocationList;
        
        public ReadResponse()
        {
        }
        
        public ReadResponse(CourseLocationList_WebService.courseLocationList courseLocationList)
        {
            this.courseLocationList = courseLocationList;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadByRecId", WrapperNamespace="urn:microsoft-dynamics-schemas/page/courselocationlist", IsWrapped=true)]
    public partial class ReadByRecIdRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/courselocationlist", Order=0)]
        public string recId;
        
        public ReadByRecIdRequest()
        {
        }
        
        public ReadByRecIdRequest(string recId)
        {
            this.recId = recId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadByRecId_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/courselocationlist", IsWrapped=true)]
    public partial class ReadByRecIdResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/courselocationlist", Order=0)]
        public CourseLocationList_WebService.courseLocationList courseLocationList;
        
        public ReadByRecIdResponse()
        {
        }
        
        public ReadByRecIdResponse(CourseLocationList_WebService.courseLocationList courseLocationList)
        {
            this.courseLocationList = courseLocationList;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadMultiple", WrapperNamespace="urn:microsoft-dynamics-schemas/page/courselocationlist", IsWrapped=true)]
    public partial class ReadMultipleRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/courselocationlist", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("filter")]
        public CourseLocationList_WebService.courseLocationList_Filter[] filter;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/courselocationlist", Order=1)]
        public string bookmarkKey;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/courselocationlist", Order=2)]
        public int setSize;
        
        public ReadMultipleRequest()
        {
        }
        
        public ReadMultipleRequest(CourseLocationList_WebService.courseLocationList_Filter[] filter, string bookmarkKey, int setSize)
        {
            this.filter = filter;
            this.bookmarkKey = bookmarkKey;
            this.setSize = setSize;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadMultiple_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/courselocationlist", IsWrapped=true)]
    public partial class ReadMultipleResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/courselocationlist", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public CourseLocationList_WebService.courseLocationList[] ReadMultiple_Result;
        
        public ReadMultipleResponse()
        {
        }
        
        public ReadMultipleResponse(CourseLocationList_WebService.courseLocationList[] ReadMultiple_Result)
        {
            this.ReadMultiple_Result = ReadMultiple_Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IsUpdated", WrapperNamespace="urn:microsoft-dynamics-schemas/page/courselocationlist", IsWrapped=true)]
    public partial class IsUpdatedRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/courselocationlist", Order=0)]
        public string Key;
        
        public IsUpdatedRequest()
        {
        }
        
        public IsUpdatedRequest(string Key)
        {
            this.Key = Key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IsUpdated_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/courselocationlist", IsWrapped=true)]
    public partial class IsUpdatedResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/courselocationlist", Order=0)]
        public bool IsUpdated_Result;
        
        public IsUpdatedResponse()
        {
        }
        
        public IsUpdatedResponse(bool IsUpdated_Result)
        {
            this.IsUpdated_Result = IsUpdated_Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetRecIdFromKey", WrapperNamespace="urn:microsoft-dynamics-schemas/page/courselocationlist", IsWrapped=true)]
    public partial class GetRecIdFromKeyRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/courselocationlist", Order=0)]
        public string Key;
        
        public GetRecIdFromKeyRequest()
        {
        }
        
        public GetRecIdFromKeyRequest(string Key)
        {
            this.Key = Key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetRecIdFromKey_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/courselocationlist", IsWrapped=true)]
    public partial class GetRecIdFromKeyResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/courselocationlist", Order=0)]
        public string GetRecIdFromKey_Result;
        
        public GetRecIdFromKeyResponse()
        {
        }
        
        public GetRecIdFromKeyResponse(string GetRecIdFromKey_Result)
        {
            this.GetRecIdFromKey_Result = GetRecIdFromKey_Result;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    public interface CourseLocationList_ServiceChannel : CourseLocationList_WebService.CourseLocationList_Service, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    public partial class CourseLocationList_ServiceClient : System.ServiceModel.ClientBase<CourseLocationList_WebService.CourseLocationList_Service>, CourseLocationList_WebService.CourseLocationList_Service
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public CourseLocationList_ServiceClient() : 
                base(CourseLocationList_ServiceClient.GetDefaultBinding(), CourseLocationList_ServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.CourseLocationList_Service.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CourseLocationList_ServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(CourseLocationList_ServiceClient.GetBindingForEndpoint(endpointConfiguration), CourseLocationList_ServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CourseLocationList_ServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(CourseLocationList_ServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CourseLocationList_ServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(CourseLocationList_ServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CourseLocationList_ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CourseLocationList_WebService.ReadResponse> CourseLocationList_WebService.CourseLocationList_Service.ReadAsync(CourseLocationList_WebService.ReadRequest request)
        {
            return base.Channel.ReadAsync(request);
        }
        
        public System.Threading.Tasks.Task<CourseLocationList_WebService.ReadResponse> ReadAsync(string No)
        {
            CourseLocationList_WebService.ReadRequest inValue = new CourseLocationList_WebService.ReadRequest();
            inValue.No = No;
            return ((CourseLocationList_WebService.CourseLocationList_Service)(this)).ReadAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CourseLocationList_WebService.ReadByRecIdResponse> CourseLocationList_WebService.CourseLocationList_Service.ReadByRecIdAsync(CourseLocationList_WebService.ReadByRecIdRequest request)
        {
            return base.Channel.ReadByRecIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<CourseLocationList_WebService.ReadByRecIdResponse> ReadByRecIdAsync(string recId)
        {
            CourseLocationList_WebService.ReadByRecIdRequest inValue = new CourseLocationList_WebService.ReadByRecIdRequest();
            inValue.recId = recId;
            return ((CourseLocationList_WebService.CourseLocationList_Service)(this)).ReadByRecIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CourseLocationList_WebService.ReadMultipleResponse> CourseLocationList_WebService.CourseLocationList_Service.ReadMultipleAsync(CourseLocationList_WebService.ReadMultipleRequest request)
        {
            return base.Channel.ReadMultipleAsync(request);
        }
        
        public System.Threading.Tasks.Task<CourseLocationList_WebService.ReadMultipleResponse> ReadMultipleAsync(CourseLocationList_WebService.courseLocationList_Filter[] filter, string bookmarkKey, int setSize)
        {
            CourseLocationList_WebService.ReadMultipleRequest inValue = new CourseLocationList_WebService.ReadMultipleRequest();
            inValue.filter = filter;
            inValue.bookmarkKey = bookmarkKey;
            inValue.setSize = setSize;
            return ((CourseLocationList_WebService.CourseLocationList_Service)(this)).ReadMultipleAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CourseLocationList_WebService.IsUpdatedResponse> CourseLocationList_WebService.CourseLocationList_Service.IsUpdatedAsync(CourseLocationList_WebService.IsUpdatedRequest request)
        {
            return base.Channel.IsUpdatedAsync(request);
        }
        
        public System.Threading.Tasks.Task<CourseLocationList_WebService.IsUpdatedResponse> IsUpdatedAsync(string Key)
        {
            CourseLocationList_WebService.IsUpdatedRequest inValue = new CourseLocationList_WebService.IsUpdatedRequest();
            inValue.Key = Key;
            return ((CourseLocationList_WebService.CourseLocationList_Service)(this)).IsUpdatedAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CourseLocationList_WebService.GetRecIdFromKeyResponse> CourseLocationList_WebService.CourseLocationList_Service.GetRecIdFromKeyAsync(CourseLocationList_WebService.GetRecIdFromKeyRequest request)
        {
            return base.Channel.GetRecIdFromKeyAsync(request);
        }
        
        public System.Threading.Tasks.Task<CourseLocationList_WebService.GetRecIdFromKeyResponse> GetRecIdFromKeyAsync(string Key)
        {
            CourseLocationList_WebService.GetRecIdFromKeyRequest inValue = new CourseLocationList_WebService.GetRecIdFromKeyRequest();
            inValue.Key = Key;
            return ((CourseLocationList_WebService.CourseLocationList_Service)(this)).GetRecIdFromKeyAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.CourseLocationList_Service))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.CourseLocationList_Service))
            {
                return new System.ServiceModel.EndpointAddress("https://consulthidanapi.azure-api.net/nav/courselocationlist");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return CourseLocationList_ServiceClient.GetBindingForEndpoint(EndpointConfiguration.CourseLocationList_Service);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return CourseLocationList_ServiceClient.GetEndpointAddress(EndpointConfiguration.CourseLocationList_Service);
        }
        
        public enum EndpointConfiguration
        {
            
            CourseLocationList_Service,
        }
    }
}
