//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TN_CourseSessionTeacher_WebService
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:microsoft-dynamics-schemas/page/tn_coursesessionteacher", ConfigurationName="TN_CourseSessionTeacher_WebService.TN_CourseSessionTeacher_Service")]
    public interface TN_CourseSessionTeacher_Service
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/tn_coursesessionteacher:Read", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<TN_CourseSessionTeacher_WebService.ReadResponse> ReadAsync(TN_CourseSessionTeacher_WebService.ReadRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/tn_coursesessionteacher:ReadByRecId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<TN_CourseSessionTeacher_WebService.ReadByRecIdResponse> ReadByRecIdAsync(TN_CourseSessionTeacher_WebService.ReadByRecIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/tn_coursesessionteacher:ReadMultiple", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<TN_CourseSessionTeacher_WebService.ReadMultipleResponse> ReadMultipleAsync(TN_CourseSessionTeacher_WebService.ReadMultipleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/tn_coursesessionteacher:IsUpdated", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<TN_CourseSessionTeacher_WebService.IsUpdatedResponse> IsUpdatedAsync(TN_CourseSessionTeacher_WebService.IsUpdatedRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/tn_coursesessionteacher:GetRecIdFromKey", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<TN_CourseSessionTeacher_WebService.GetRecIdFromKeyResponse> GetRecIdFromKeyAsync(TN_CourseSessionTeacher_WebService.GetRecIdFromKeyRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/tn_coursesessionteacher")]
    public partial class TN_CourseSessionTeacher
    {
        
        private string keyField;
        
        private string school_Department_NoField;
        
        private string school_Department_NameField;
        
        private int entry_NoField;
        
        private bool entry_NoFieldSpecified;
        
        private string course_Header_NoField;
        
        private string course_Header_DescriptionField;
        
        private Week_Day week_DayField;
        
        private bool week_DayFieldSpecified;
        
        private System.DateTime dateField;
        
        private bool dateFieldSpecified;
        
        private System.DateTime from_TimeField;
        
        private bool from_TimeFieldSpecified;
        
        private System.DateTime to_TimeField;
        
        private bool to_TimeFieldSpecified;
        
        private decimal qty_LessonsField;
        
        private bool qty_LessonsFieldSpecified;
        
        private Cancelled cancelledField;
        
        private bool cancelledFieldSpecified;
        
        private string class_Room_NoField;
        
        private string class_Room_NameField;
        
        private string course_Location_NoField;
        
        private string course_Location_NameField;
        
        private string location_AddressField;
        
        private string location_Post_CodeField;
        
        private string location_ByField;
        
        private decimal location_LatitudeField;
        
        private bool location_LatitudeFieldSpecified;
        
        private decimal location_LongtitudeField;
        
        private bool location_LongtitudeFieldSpecified;
        
        private string teacher_NoField;
        
        private string teacher_NameField;
        
        private bool primary_TeacherField;
        
        private bool primary_TeacherFieldSpecified;
        
        private decimal salary_RateField;
        
        private bool salary_RateFieldSpecified;
        
        private Course_Header_Status course_Header_StatusField;
        
        private bool course_Header_StatusFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Key
        {
            get
            {
                return this.keyField;
            }
            set
            {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string School_Department_No
        {
            get
            {
                return this.school_Department_NoField;
            }
            set
            {
                this.school_Department_NoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string School_Department_Name
        {
            get
            {
                return this.school_Department_NameField;
            }
            set
            {
                this.school_Department_NameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int Entry_No
        {
            get
            {
                return this.entry_NoField;
            }
            set
            {
                this.entry_NoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Entry_NoSpecified
        {
            get
            {
                return this.entry_NoFieldSpecified;
            }
            set
            {
                this.entry_NoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Course_Header_No
        {
            get
            {
                return this.course_Header_NoField;
            }
            set
            {
                this.course_Header_NoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Course_Header_Description
        {
            get
            {
                return this.course_Header_DescriptionField;
            }
            set
            {
                this.course_Header_DescriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public Week_Day Week_Day
        {
            get
            {
                return this.week_DayField;
            }
            set
            {
                this.week_DayField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Week_DaySpecified
        {
            get
            {
                return this.week_DayFieldSpecified;
            }
            set
            {
                this.week_DayFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=7)]
        public System.DateTime Date
        {
            get
            {
                return this.dateField;
            }
            set
            {
                this.dateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DateSpecified
        {
            get
            {
                return this.dateFieldSpecified;
            }
            set
            {
                this.dateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="time", Order=8)]
        public System.DateTime From_Time
        {
            get
            {
                return this.from_TimeField;
            }
            set
            {
                this.from_TimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool From_TimeSpecified
        {
            get
            {
                return this.from_TimeFieldSpecified;
            }
            set
            {
                this.from_TimeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="time", Order=9)]
        public System.DateTime To_Time
        {
            get
            {
                return this.to_TimeField;
            }
            set
            {
                this.to_TimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool To_TimeSpecified
        {
            get
            {
                return this.to_TimeFieldSpecified;
            }
            set
            {
                this.to_TimeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public decimal Qty_Lessons
        {
            get
            {
                return this.qty_LessonsField;
            }
            set
            {
                this.qty_LessonsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Qty_LessonsSpecified
        {
            get
            {
                return this.qty_LessonsFieldSpecified;
            }
            set
            {
                this.qty_LessonsFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public Cancelled Cancelled
        {
            get
            {
                return this.cancelledField;
            }
            set
            {
                this.cancelledField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CancelledSpecified
        {
            get
            {
                return this.cancelledFieldSpecified;
            }
            set
            {
                this.cancelledFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string Class_Room_No
        {
            get
            {
                return this.class_Room_NoField;
            }
            set
            {
                this.class_Room_NoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string Class_Room_Name
        {
            get
            {
                return this.class_Room_NameField;
            }
            set
            {
                this.class_Room_NameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string Course_Location_No
        {
            get
            {
                return this.course_Location_NoField;
            }
            set
            {
                this.course_Location_NoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string Course_Location_Name
        {
            get
            {
                return this.course_Location_NameField;
            }
            set
            {
                this.course_Location_NameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string Location_Address
        {
            get
            {
                return this.location_AddressField;
            }
            set
            {
                this.location_AddressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string Location_Post_Code
        {
            get
            {
                return this.location_Post_CodeField;
            }
            set
            {
                this.location_Post_CodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string Location_By
        {
            get
            {
                return this.location_ByField;
            }
            set
            {
                this.location_ByField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public decimal Location_Latitude
        {
            get
            {
                return this.location_LatitudeField;
            }
            set
            {
                this.location_LatitudeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Location_LatitudeSpecified
        {
            get
            {
                return this.location_LatitudeFieldSpecified;
            }
            set
            {
                this.location_LatitudeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public decimal Location_Longtitude
        {
            get
            {
                return this.location_LongtitudeField;
            }
            set
            {
                this.location_LongtitudeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Location_LongtitudeSpecified
        {
            get
            {
                return this.location_LongtitudeFieldSpecified;
            }
            set
            {
                this.location_LongtitudeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public string Teacher_No
        {
            get
            {
                return this.teacher_NoField;
            }
            set
            {
                this.teacher_NoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public string Teacher_Name
        {
            get
            {
                return this.teacher_NameField;
            }
            set
            {
                this.teacher_NameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public bool Primary_Teacher
        {
            get
            {
                return this.primary_TeacherField;
            }
            set
            {
                this.primary_TeacherField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Primary_TeacherSpecified
        {
            get
            {
                return this.primary_TeacherFieldSpecified;
            }
            set
            {
                this.primary_TeacherFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public decimal Salary_Rate
        {
            get
            {
                return this.salary_RateField;
            }
            set
            {
                this.salary_RateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Salary_RateSpecified
        {
            get
            {
                return this.salary_RateFieldSpecified;
            }
            set
            {
                this.salary_RateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=25)]
        public Course_Header_Status Course_Header_Status
        {
            get
            {
                return this.course_Header_StatusField;
            }
            set
            {
                this.course_Header_StatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Course_Header_StatusSpecified
        {
            get
            {
                return this.course_Header_StatusFieldSpecified;
            }
            set
            {
                this.course_Header_StatusFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/tn_coursesessionteacher")]
    public enum Week_Day
    {
        
        /// <remarks/>
        Monday,
        
        /// <remarks/>
        Thuesday,
        
        /// <remarks/>
        Wednesday,
        
        /// <remarks/>
        Thursday,
        
        /// <remarks/>
        Friday,
        
        /// <remarks/>
        Saturday,
        
        /// <remarks/>
        Sunday,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/tn_coursesessionteacher")]
    public enum Cancelled
    {
        
        /// <remarks/>
        _blank_,
        
        /// <remarks/>
        Cancelled,
        
        /// <remarks/>
        Moved,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/tn_coursesessionteacher")]
    public enum Course_Header_Status
    {
        
        /// <remarks/>
        Planning,
        
        /// <remarks/>
        booked,
        
        /// <remarks/>
        Cancelled,
        
        /// <remarks/>
        Completed,
        
        /// <remarks/>
        Launched,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/tn_coursesessionteacher")]
    public partial class TN_CourseSessionTeacher_Filter
    {
        
        private TN_CourseSessionTeacher_Fields fieldField;
        
        private string criteriaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public TN_CourseSessionTeacher_Fields Field
        {
            get
            {
                return this.fieldField;
            }
            set
            {
                this.fieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Criteria
        {
            get
            {
                return this.criteriaField;
            }
            set
            {
                this.criteriaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/tn_coursesessionteacher")]
    public enum TN_CourseSessionTeacher_Fields
    {
        
        /// <remarks/>
        School_Department_No,
        
        /// <remarks/>
        School_Department_Name,
        
        /// <remarks/>
        Entry_No,
        
        /// <remarks/>
        Course_Header_No,
        
        /// <remarks/>
        Course_Header_Description,
        
        /// <remarks/>
        Week_Day,
        
        /// <remarks/>
        Date,
        
        /// <remarks/>
        From_Time,
        
        /// <remarks/>
        To_Time,
        
        /// <remarks/>
        Qty_Lessons,
        
        /// <remarks/>
        Cancelled,
        
        /// <remarks/>
        Class_Room_No,
        
        /// <remarks/>
        Class_Room_Name,
        
        /// <remarks/>
        Course_Location_No,
        
        /// <remarks/>
        Course_Location_Name,
        
        /// <remarks/>
        Location_Address,
        
        /// <remarks/>
        Location_Post_Code,
        
        /// <remarks/>
        Location_By,
        
        /// <remarks/>
        Location_Latitude,
        
        /// <remarks/>
        Location_Longtitude,
        
        /// <remarks/>
        Teacher_No,
        
        /// <remarks/>
        Teacher_Name,
        
        /// <remarks/>
        Primary_Teacher,
        
        /// <remarks/>
        Salary_Rate,
        
        /// <remarks/>
        Course_Header_Status,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Read", WrapperNamespace="urn:microsoft-dynamics-schemas/page/tn_coursesessionteacher", IsWrapped=true)]
    public partial class ReadRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/tn_coursesessionteacher", Order=0)]
        public string Course_Header_No;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/tn_coursesessionteacher", Order=1)]
        public int Entry_No;
        
        public ReadRequest()
        {
        }
        
        public ReadRequest(string Course_Header_No, int Entry_No)
        {
            this.Course_Header_No = Course_Header_No;
            this.Entry_No = Entry_No;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Read_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/tn_coursesessionteacher", IsWrapped=true)]
    public partial class ReadResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/tn_coursesessionteacher", Order=0)]
        public TN_CourseSessionTeacher_WebService.TN_CourseSessionTeacher TN_CourseSessionTeacher;
        
        public ReadResponse()
        {
        }
        
        public ReadResponse(TN_CourseSessionTeacher_WebService.TN_CourseSessionTeacher TN_CourseSessionTeacher)
        {
            this.TN_CourseSessionTeacher = TN_CourseSessionTeacher;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadByRecId", WrapperNamespace="urn:microsoft-dynamics-schemas/page/tn_coursesessionteacher", IsWrapped=true)]
    public partial class ReadByRecIdRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/tn_coursesessionteacher", Order=0)]
        public string recId;
        
        public ReadByRecIdRequest()
        {
        }
        
        public ReadByRecIdRequest(string recId)
        {
            this.recId = recId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadByRecId_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/tn_coursesessionteacher", IsWrapped=true)]
    public partial class ReadByRecIdResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/tn_coursesessionteacher", Order=0)]
        public TN_CourseSessionTeacher_WebService.TN_CourseSessionTeacher TN_CourseSessionTeacher;
        
        public ReadByRecIdResponse()
        {
        }
        
        public ReadByRecIdResponse(TN_CourseSessionTeacher_WebService.TN_CourseSessionTeacher TN_CourseSessionTeacher)
        {
            this.TN_CourseSessionTeacher = TN_CourseSessionTeacher;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadMultiple", WrapperNamespace="urn:microsoft-dynamics-schemas/page/tn_coursesessionteacher", IsWrapped=true)]
    public partial class ReadMultipleRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/tn_coursesessionteacher", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("filter")]
        public TN_CourseSessionTeacher_WebService.TN_CourseSessionTeacher_Filter[] filter;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/tn_coursesessionteacher", Order=1)]
        public string bookmarkKey;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/tn_coursesessionteacher", Order=2)]
        public int setSize;
        
        public ReadMultipleRequest()
        {
        }
        
        public ReadMultipleRequest(TN_CourseSessionTeacher_WebService.TN_CourseSessionTeacher_Filter[] filter, string bookmarkKey, int setSize)
        {
            this.filter = filter;
            this.bookmarkKey = bookmarkKey;
            this.setSize = setSize;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadMultiple_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/tn_coursesessionteacher", IsWrapped=true)]
    public partial class ReadMultipleResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/tn_coursesessionteacher", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public TN_CourseSessionTeacher_WebService.TN_CourseSessionTeacher[] ReadMultiple_Result;
        
        public ReadMultipleResponse()
        {
        }
        
        public ReadMultipleResponse(TN_CourseSessionTeacher_WebService.TN_CourseSessionTeacher[] ReadMultiple_Result)
        {
            this.ReadMultiple_Result = ReadMultiple_Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IsUpdated", WrapperNamespace="urn:microsoft-dynamics-schemas/page/tn_coursesessionteacher", IsWrapped=true)]
    public partial class IsUpdatedRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/tn_coursesessionteacher", Order=0)]
        public string Key;
        
        public IsUpdatedRequest()
        {
        }
        
        public IsUpdatedRequest(string Key)
        {
            this.Key = Key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IsUpdated_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/tn_coursesessionteacher", IsWrapped=true)]
    public partial class IsUpdatedResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/tn_coursesessionteacher", Order=0)]
        public bool IsUpdated_Result;
        
        public IsUpdatedResponse()
        {
        }
        
        public IsUpdatedResponse(bool IsUpdated_Result)
        {
            this.IsUpdated_Result = IsUpdated_Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetRecIdFromKey", WrapperNamespace="urn:microsoft-dynamics-schemas/page/tn_coursesessionteacher", IsWrapped=true)]
    public partial class GetRecIdFromKeyRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/tn_coursesessionteacher", Order=0)]
        public string Key;
        
        public GetRecIdFromKeyRequest()
        {
        }
        
        public GetRecIdFromKeyRequest(string Key)
        {
            this.Key = Key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetRecIdFromKey_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/tn_coursesessionteacher", IsWrapped=true)]
    public partial class GetRecIdFromKeyResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/tn_coursesessionteacher", Order=0)]
        public string GetRecIdFromKey_Result;
        
        public GetRecIdFromKeyResponse()
        {
        }
        
        public GetRecIdFromKeyResponse(string GetRecIdFromKey_Result)
        {
            this.GetRecIdFromKey_Result = GetRecIdFromKey_Result;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface TN_CourseSessionTeacher_ServiceChannel : TN_CourseSessionTeacher_WebService.TN_CourseSessionTeacher_Service, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class TN_CourseSessionTeacher_ServiceClient : System.ServiceModel.ClientBase<TN_CourseSessionTeacher_WebService.TN_CourseSessionTeacher_Service>, TN_CourseSessionTeacher_WebService.TN_CourseSessionTeacher_Service
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public TN_CourseSessionTeacher_ServiceClient() : 
                base(TN_CourseSessionTeacher_ServiceClient.GetDefaultBinding(), TN_CourseSessionTeacher_ServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.TN_CourseSessionTeacher_Service.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TN_CourseSessionTeacher_ServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(TN_CourseSessionTeacher_ServiceClient.GetBindingForEndpoint(endpointConfiguration), TN_CourseSessionTeacher_ServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TN_CourseSessionTeacher_ServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(TN_CourseSessionTeacher_ServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TN_CourseSessionTeacher_ServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(TN_CourseSessionTeacher_ServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TN_CourseSessionTeacher_ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TN_CourseSessionTeacher_WebService.ReadResponse> TN_CourseSessionTeacher_WebService.TN_CourseSessionTeacher_Service.ReadAsync(TN_CourseSessionTeacher_WebService.ReadRequest request)
        {
            return base.Channel.ReadAsync(request);
        }
        
        public System.Threading.Tasks.Task<TN_CourseSessionTeacher_WebService.ReadResponse> ReadAsync(string Course_Header_No, int Entry_No)
        {
            TN_CourseSessionTeacher_WebService.ReadRequest inValue = new TN_CourseSessionTeacher_WebService.ReadRequest();
            inValue.Course_Header_No = Course_Header_No;
            inValue.Entry_No = Entry_No;
            return ((TN_CourseSessionTeacher_WebService.TN_CourseSessionTeacher_Service)(this)).ReadAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TN_CourseSessionTeacher_WebService.ReadByRecIdResponse> TN_CourseSessionTeacher_WebService.TN_CourseSessionTeacher_Service.ReadByRecIdAsync(TN_CourseSessionTeacher_WebService.ReadByRecIdRequest request)
        {
            return base.Channel.ReadByRecIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<TN_CourseSessionTeacher_WebService.ReadByRecIdResponse> ReadByRecIdAsync(string recId)
        {
            TN_CourseSessionTeacher_WebService.ReadByRecIdRequest inValue = new TN_CourseSessionTeacher_WebService.ReadByRecIdRequest();
            inValue.recId = recId;
            return ((TN_CourseSessionTeacher_WebService.TN_CourseSessionTeacher_Service)(this)).ReadByRecIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TN_CourseSessionTeacher_WebService.ReadMultipleResponse> TN_CourseSessionTeacher_WebService.TN_CourseSessionTeacher_Service.ReadMultipleAsync(TN_CourseSessionTeacher_WebService.ReadMultipleRequest request)
        {
            return base.Channel.ReadMultipleAsync(request);
        }
        
        public System.Threading.Tasks.Task<TN_CourseSessionTeacher_WebService.ReadMultipleResponse> ReadMultipleAsync(TN_CourseSessionTeacher_WebService.TN_CourseSessionTeacher_Filter[] filter, string bookmarkKey, int setSize)
        {
            TN_CourseSessionTeacher_WebService.ReadMultipleRequest inValue = new TN_CourseSessionTeacher_WebService.ReadMultipleRequest();
            inValue.filter = filter;
            inValue.bookmarkKey = bookmarkKey;
            inValue.setSize = setSize;
            return ((TN_CourseSessionTeacher_WebService.TN_CourseSessionTeacher_Service)(this)).ReadMultipleAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TN_CourseSessionTeacher_WebService.IsUpdatedResponse> TN_CourseSessionTeacher_WebService.TN_CourseSessionTeacher_Service.IsUpdatedAsync(TN_CourseSessionTeacher_WebService.IsUpdatedRequest request)
        {
            return base.Channel.IsUpdatedAsync(request);
        }
        
        public System.Threading.Tasks.Task<TN_CourseSessionTeacher_WebService.IsUpdatedResponse> IsUpdatedAsync(string Key)
        {
            TN_CourseSessionTeacher_WebService.IsUpdatedRequest inValue = new TN_CourseSessionTeacher_WebService.IsUpdatedRequest();
            inValue.Key = Key;
            return ((TN_CourseSessionTeacher_WebService.TN_CourseSessionTeacher_Service)(this)).IsUpdatedAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TN_CourseSessionTeacher_WebService.GetRecIdFromKeyResponse> TN_CourseSessionTeacher_WebService.TN_CourseSessionTeacher_Service.GetRecIdFromKeyAsync(TN_CourseSessionTeacher_WebService.GetRecIdFromKeyRequest request)
        {
            return base.Channel.GetRecIdFromKeyAsync(request);
        }
        
        public System.Threading.Tasks.Task<TN_CourseSessionTeacher_WebService.GetRecIdFromKeyResponse> GetRecIdFromKeyAsync(string Key)
        {
            TN_CourseSessionTeacher_WebService.GetRecIdFromKeyRequest inValue = new TN_CourseSessionTeacher_WebService.GetRecIdFromKeyRequest();
            inValue.Key = Key;
            return ((TN_CourseSessionTeacher_WebService.TN_CourseSessionTeacher_Service)(this)).GetRecIdFromKeyAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.TN_CourseSessionTeacher_Service))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.TN_CourseSessionTeacher_Service))
            {
                return new System.ServiceModel.EndpointAddress("https://iqiapimanagement-asa-test.azure-api.net/tn_coursesessionteacher");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return TN_CourseSessionTeacher_ServiceClient.GetBindingForEndpoint(EndpointConfiguration.TN_CourseSessionTeacher_Service);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return TN_CourseSessionTeacher_ServiceClient.GetEndpointAddress(EndpointConfiguration.TN_CourseSessionTeacher_Service);
        }
        
        public enum EndpointConfiguration
        {
            
            TN_CourseSessionTeacher_Service,
        }
    }
}
