//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseWebStatus_WebService
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/CourseWebStatus", ConfigurationName="CourseWebStatus_WebService.CourseWebStatus_Service")]
    public interface CourseWebStatus_Service
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/CourseWebStatus:GetNavOrderId", ReplyAction="*")]
        System.Threading.Tasks.Task<CourseWebStatus_WebService.GetNavOrderIdResponse> GetNavOrderIdAsync(CourseWebStatus_WebService.GetNavOrderIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/CourseWebStatus:GetOrderStatus", ReplyAction="*")]
        System.Threading.Tasks.Task<CourseWebStatus_WebService.GetOrderStatusResponse> GetOrderStatusAsync(CourseWebStatus_WebService.GetOrderStatusRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetNavOrderId", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/CourseWebStatus", IsWrapped=true)]
    public partial class GetNavOrderIdRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/CourseWebStatus", Order=0)]
        public string portalOrderId;
        
        public GetNavOrderIdRequest()
        {
        }
        
        public GetNavOrderIdRequest(string portalOrderId)
        {
            this.portalOrderId = portalOrderId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetNavOrderId_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/CourseWebStatus", IsWrapped=true)]
    public partial class GetNavOrderIdResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/CourseWebStatus", Order=0)]
        public string return_value;
        
        public GetNavOrderIdResponse()
        {
        }
        
        public GetNavOrderIdResponse(string return_value)
        {
            this.return_value = return_value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetOrderStatusRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetOrderStatus", Namespace="urn:microsoft-dynamics-schemas/codeunit/CourseWebStatus", Order=0)]
        public CourseWebStatus_WebService.GetOrderStatusRequestBody Body;
        
        public GetOrderStatusRequest()
        {
        }
        
        public GetOrderStatusRequest(CourseWebStatus_WebService.GetOrderStatusRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/CourseWebStatus")]
    public partial class GetOrderStatusRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string portalOrderId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string navOrderId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string errorMessage;
        
        public GetOrderStatusRequestBody()
        {
        }
        
        public GetOrderStatusRequestBody(string portalOrderId, string navOrderId, string errorMessage)
        {
            this.portalOrderId = portalOrderId;
            this.navOrderId = navOrderId;
            this.errorMessage = errorMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetOrderStatusResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetOrderStatus_Result", Namespace="urn:microsoft-dynamics-schemas/codeunit/CourseWebStatus", Order=0)]
        public CourseWebStatus_WebService.GetOrderStatusResponseBody Body;
        
        public GetOrderStatusResponse()
        {
        }
        
        public GetOrderStatusResponse(CourseWebStatus_WebService.GetOrderStatusResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/CourseWebStatus")]
    public partial class GetOrderStatusResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string return_value;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string errorMessage;
        
        public GetOrderStatusResponseBody()
        {
        }
        
        public GetOrderStatusResponseBody(string return_value, string errorMessage)
        {
            this.return_value = return_value;
            this.errorMessage = errorMessage;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    public interface CourseWebStatus_ServiceChannel : CourseWebStatus_WebService.CourseWebStatus_Service, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    public partial class CourseWebStatus_ServiceClient : System.ServiceModel.ClientBase<CourseWebStatus_WebService.CourseWebStatus_Service>, CourseWebStatus_WebService.CourseWebStatus_Service
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public CourseWebStatus_ServiceClient() : 
                base(CourseWebStatus_ServiceClient.GetDefaultBinding(), CourseWebStatus_ServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.CourseWebStatus_Service.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CourseWebStatus_ServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(CourseWebStatus_ServiceClient.GetBindingForEndpoint(endpointConfiguration), CourseWebStatus_ServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CourseWebStatus_ServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(CourseWebStatus_ServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CourseWebStatus_ServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(CourseWebStatus_ServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CourseWebStatus_ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CourseWebStatus_WebService.GetNavOrderIdResponse> CourseWebStatus_WebService.CourseWebStatus_Service.GetNavOrderIdAsync(CourseWebStatus_WebService.GetNavOrderIdRequest request)
        {
            return base.Channel.GetNavOrderIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<CourseWebStatus_WebService.GetNavOrderIdResponse> GetNavOrderIdAsync(string portalOrderId)
        {
            CourseWebStatus_WebService.GetNavOrderIdRequest inValue = new CourseWebStatus_WebService.GetNavOrderIdRequest();
            inValue.portalOrderId = portalOrderId;
            return ((CourseWebStatus_WebService.CourseWebStatus_Service)(this)).GetNavOrderIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CourseWebStatus_WebService.GetOrderStatusResponse> CourseWebStatus_WebService.CourseWebStatus_Service.GetOrderStatusAsync(CourseWebStatus_WebService.GetOrderStatusRequest request)
        {
            return base.Channel.GetOrderStatusAsync(request);
        }
        
        public System.Threading.Tasks.Task<CourseWebStatus_WebService.GetOrderStatusResponse> GetOrderStatusAsync(string portalOrderId, string navOrderId, string errorMessage)
        {
            CourseWebStatus_WebService.GetOrderStatusRequest inValue = new CourseWebStatus_WebService.GetOrderStatusRequest();
            inValue.Body = new CourseWebStatus_WebService.GetOrderStatusRequestBody();
            inValue.Body.portalOrderId = portalOrderId;
            inValue.Body.navOrderId = navOrderId;
            inValue.Body.errorMessage = errorMessage;
            return ((CourseWebStatus_WebService.CourseWebStatus_Service)(this)).GetOrderStatusAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.CourseWebStatus_Service))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.CourseWebStatus_Service))
            {
                return new System.ServiceModel.EndpointAddress("https://iqiapimanagement-asa-dev-northeurope-01.regional.azure-api.net/coursewebs" +
                        "tatus");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return CourseWebStatus_ServiceClient.GetBindingForEndpoint(EndpointConfiguration.CourseWebStatus_Service);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return CourseWebStatus_ServiceClient.GetEndpointAddress(EndpointConfiguration.CourseWebStatus_Service);
        }
        
        public enum EndpointConfiguration
        {
            
            CourseWebStatus_Service,
        }
    }
}
